
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('ship_specs1').del()
    .then(function () {
      // Inserts seed entries
      return knex('ship_specs1').insert([
        {
          id: "1",
          afterburner_speed: "1140",
          beam: "8.0",
          cargocapacity: null,
          height: "4.0",
          length: "18.0",
          manufacturer_id: "1",
          mass: "25172",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "190",
          size: "small",
          time_modified: "4 months ago",
          type: "multi",
          xaxis_acceleration: "43.0",
          yaw_max: "70.0",
          yaxis_acceleration: "45.7",
          zaxis_acceleration: "44.2",
          description: "The Aurora is the modern-day descendant of the Roberts Space Industries X-7 spacecraft which tested the very first jump engines. Utilitarian to a T, the Aurora Essential is the perfect choice for new ship owners: versatile enough to tackle a myriad of challenges, yet with a straightforward and intuitive design.",
          url: "/pledge/ships/rsi-aurora/Aurora-ES"
        },
        {
          id: "3",
          afterburner_speed: "1200",
          beam: "8.0",
          cargocapacity: null,
          height: "4.0",
          length: "18.0",
          manufacturer_id: "1",
          mass: "25017",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "190",
          size: "small",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: "43.0",
          yaw_max: "70.0",
          yaxis_acceleration: "45.7",
          zaxis_acceleration: "44.2",
          description: "Be proud of your roots with the brand-new Aurora Deluxe, built for the discerning pilot who never forgets where he or she came from. The LX features patent leather interior to guarantee comfort for those long stretches in the deep black.",
          url: "/pledge/ships/rsi-aurora/Aurora-LX"
        },
        {
          id: "4",
          afterburner_speed: "1210",
          beam: "8.0",
          cargocapacity: null,
          height: "4.0",
          length: "18.0",
          manufacturer_id: "1",
          mass: "25017",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "195",
          size: "small",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "42.9",
          yaw_max: "70.0",
          yaxis_acceleration: "45.6",
          zaxis_acceleration: "44.1",
          description: "Perhaps you're looking for something that offers carrying capacity but has combat capabilities too? The Aurora Marque comes with a pair of Behring-quality lasers and a high quality gun cooler system.",
          url: "/pledge/ships/rsi-aurora/Aurora-MR"
        },
        {
          id: "5",
          afterburner_speed: "1095",
          beam: "8.0",
          cargocapacity: "6",
          height: "4.0",
          length: "18.0",
          manufacturer_id: "1",
          mass: "25172",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "185",
          size: "small",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "42.7",
          yaw_max: "70.0",
          yaxis_acceleration: "45.3",
          zaxis_acceleration: "43.9",
          description: "Customized for mercantile and trading excursions, the Aurora Clipper is the perfect vessel for aspiring entrepreneurs and seasoned traders alike. Thanks to its expanded cargo capacity, the Clipper ups the ante for personal merchant craft.",
          url: "/pledge/ships/rsi-aurora/Aurora-CL"
        },
        {
          id: "6",
          afterburner_speed: "1210",
          beam: "8.0",
          cargocapacity: null,
          height: "4.0",
          length: "18.0",
          manufacturer_id: "1",
          mass: "25338",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "185",
          size: "small",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "42.7",
          yaw_max: "70.0",
          yaxis_acceleration: "45.3",
          zaxis_acceleration: "43.9",
          description: "With a more robust shield generator and a pair of additional weapon hard points, the Legionnaire is a dedicated combat fighter, built to handle any obstacle the universe can throw at you.",
          url: "/pledge/ships/rsi-aurora/Aurora-LN"
        },
        {
          id: "7",
          afterburner_speed: "1190",
          beam: "17.0",
          cargocapacity: "8",
          height: "8.0",
          length: "27.0",
          manufacturer_id: "6",
          mass: "66320",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "85.0",
          production_note: "Rework complete (3.5.0)",
          production_status: "flight-ready",
          roll_max: "120.0",
          scm_speed: "204",
          size: "small",
          time_modified: "3 weeks ago",
          type: "exploration",
          xaxis_acceleration: "68.0",
          yaw_max: "85.0",
          yaxis_acceleration: "80.3",
          zaxis_acceleration: "71.7",
          description: "If you're going to travel the stars... why not do it in style? The 300i is Origin Jumpworks' premiere luxury spacecraft. It is a sleek, silver killer that sends as much of a message with its silhouette as it does with its weaponry.",
          url: "/pledge/ships/origin-300/300i"
        },
        {
          id: "8",
          afterburner_speed: "1225",
          beam: "17.0",
          cargocapacity: "12",
          height: "8.0",
          length: "27.0",
          manufacturer_id: "6",
          mass: "69220",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "85.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "120.0",
          scm_speed: "210",
          size: "small",
          time_modified: "2 months ago",
          type: "exploration",
          xaxis_acceleration: "71.0",
          yaw_max: "85.0",
          yaxis_acceleration: "87.2",
          zaxis_acceleration: "75.4",
          description: "Exploration is man's highest calling. Prepare to chart distant horizons with man's most sophisticated piece of technology, the ORIGIN 315p. Featuring a more robust power plant and a custom scanning package, exclusively designed by Chimera Communications.",
          url: "/pledge/ships/origin-300/315p"
        },
        {
          id: "9",
          afterburner_speed: "1315",
          beam: "17.0",
          cargocapacity: "4",
          height: "8.0",
          length: "27.0",
          manufacturer_id: "6",
          mass: "72500",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "100.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "225",
          size: "small",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: "72.1",
          yaw_max: "100.0",
          yaxis_acceleration: "96.4",
          zaxis_acceleration: "76.3",
          description: "Just because it's a rough galaxy doesn't mean you need to sacrifice your comfort: the 325a can come out on top in any dogfight. The 325a features an advanced weapon payload as well as a custom targeting system designed especially for the 325a by WillsOp.",
          url: "/pledge/ships/origin-300/325a"
        },
        {
          id: "10",
          afterburner_speed: "1345",
          beam: "17.0",
          cargocapacity: "4",
          height: "8.0",
          length: "27.0",
          manufacturer_id: "6",
          mass: "58530",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "125.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "170.0",
          scm_speed: "258",
          size: "small",
          time_modified: "2 months ago",
          type: "competition",
          xaxis_acceleration: "90.7",
          yaw_max: "125.0",
          yaxis_acceleration: "120.2",
          zaxis_acceleration: "101.5",
          description: "Origin Jumpwork’s 300 Series is the ultimate fusion of elegance and power. Every component, every part is individually calibrated, so no matter which model and options you choose, your ship will stay in perfect harmony as the ultimate in astroengineering.  By far the fastest member of the family, the 350r refocus all of the 300’s power and translates it into pure speed.\n",
          url: "/pledge/ships/origin-300/350r"
        },
        {
          id: "11",
          afterburner_speed: "1225",
          beam: "21.5",
          cargocapacity: "2",
          height: "6.5",
          length: "22.5",
          manufacturer_id: "3",
          mass: "73535",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "130.0",
          scm_speed: "235",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "74.1",
          yaw_max: "90.0",
          yaxis_acceleration: "87.7",
          zaxis_acceleration: "83.0",
          description: "To the enemy, it is a weapon never to be underestimated. To allies, it's a savior. The F7C Hornet is the same dependable and resilient multi-purpose fighter that has become the face of the UEE Navy. The F7C is the foundation to build on and meet whatever requirements you have in mind.",
          url: "/pledge/ships/anvil-hornet/F7C-Hornet"
        },
        {
          id: "122",
          afterburner_speed: "1224",
          beam: "21.5",
          cargocapacity: "0",
          height: "6.5",
          length: "22.5",
          manufacturer_id: "3",
          mass: "73535",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "80.0",
          scm_speed: "185",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "74.1",
          yaw_max: "70.0",
          yaxis_acceleration: "87.7",
          zaxis_acceleration: "83.0",
          description: "Created as part of the ‘Masters of Flight’ series in conjunction with the flight-sim Arena Commander, the Wildfire pays tribute to famed pilot Aria Reilly for her distinguished service with the legendary Squadron 42. This Hornet comes equipped with her own personally selected loadout preferences and a custom special edition livery honoring her iconic ship.\n",
          url: "/pledge/ships/anvil-hornet/F7C-Hornet-Wildfire"
        },
        {
          id: "13",
          afterburner_speed: "1225",
          beam: "21.5",
          cargocapacity: "0",
          height: "6.5",
          length: "22.5",
          manufacturer_id: "3",
          mass: "73454",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "130.0",
          scm_speed: "235",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "74.1",
          yaw_max: "90.0",
          yaxis_acceleration: "87.7",
          zaxis_acceleration: "83.0",
          description: "Through a combination of low-emission drives, low-draw weapons, and Void Armor technology capable of diffusing scans, the F7C-S Ghost is built for the pilot who wants to keep a low profile. The Ghost is capable of slipping past the most ardent of observers to accomplish whatever goal you need to accomplish. Don't worry, we won't ask.",
          url: "/pledge/ships/anvil-hornet/F7C-S-Hornet-Ghost"
        },
        {
          id: "14",
          afterburner_speed: "1215",
          beam: "21.5",
          cargocapacity: "0",
          height: "6.5",
          length: "22.5",
          manufacturer_id: "3",
          mass: "73497",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "130.0",
          scm_speed: "240",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "71.0",
          yaw_max: "90.0",
          yaxis_acceleration: "82.2",
          zaxis_acceleration: "78.5",
          description: "If the Ghost is made to hide, the Tracker is made to seek. The F7C-R Tracker boasts an advanced radar suite making it ideal for deep-space explorers who require depth and accuracy in their scan packages. Local militia and larger merc units will also repurpose Trackers to act as mobile C&amp;C ships for their squadrons.",
          url: "/pledge/ships/anvil-hornet/F7C-R-Hornet-Tracker"
        },
        {
          id: "15",
          afterburner_speed: "1220",
          beam: "24.0",
          cargocapacity: "0",
          height: "6.5",
          length: "25.5",
          manufacturer_id: "3",
          mass: "78466",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "130.0",
          scm_speed: "230",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "69.1",
          yaw_max: "90.0",
          yaxis_acceleration: "78.8",
          zaxis_acceleration: "75.6",
          description: "The closest to the Military load-out as is legally possible for a Civilian model, the F7C-M Super Hornet reattaches the ball turret and offers near milspec parts under the hood. Proving that two heads are better than one, a second seat has been added to split the logistic and combat duty, making the Super Hornet a truly terrifying mark to engage.",
          url: "/pledge/ships/anvil-hornet/F7C-M-Super-Hornet"
        },
        {
          id: "37",
          afterburner_speed: "0",
          beam: "22.0",
          cargocapacity: "0",
          height: "7.0",
          length: "22.5",
          manufacturer_id: "3",
          mass: "73317",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "small",
          time_modified: "10 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The UEE Navy's premier carrier-based fighter craft, the F7A is the front-line attack ship for military combat missions. While not outfitted for long range runs, the Hornet can take her share of hits... and dish out a consistent, powerful response.",
          url: "/pledge/ships/anvil-hornet/F7A-Hornet"
        },
        {
          id: "177",
          afterburner_speed: "1220",
          beam: "24.0",
          cargocapacity: "0",
          height: "6.5",
          length: "25.5",
          manufacturer_id: "3",
          mass: "78466",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "130.0",
          scm_speed: "230",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "69.1",
          yaw_max: "90.0",
          yaxis_acceleration: "78.8",
          zaxis_acceleration: "75.6",
          description: "Designed for pilots whose true love is the pulse-pounding thrill of a harrowing dogfight, Anvil's limited-edition Heartseeker is 'the one' for true combat die-hards. Loaded with top-of-the-line near military-spec components and four imposing Behring laser cannons, this fierce eradicator hones the legendary combat proficiency of the Super Hornet to give you the ultimate edge in space combat.",
          url: "/pledge/ships/anvil-hornet/F7C-M-Super-Hornet-Heartseeker"
        },
        {
          id: "47",
          afterburner_speed: "985",
          beam: "26.0",
          cargocapacity: "96",
          height: "14.0",
          length: "61.0",
          manufacturer_id: "1",
          mass: "439108",
          max_crew: "4",
          min_crew: "3",
          pitch_max: "25.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "50.0",
          scm_speed: "190",
          size: "large",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: "19.0",
          yaw_max: "25.0",
          yaxis_acceleration: "34.7",
          zaxis_acceleration: "23.3",
          description: "Explore any distant horizons! The Constellation Aquila features a redesigned cockpit for maximum visibility, advanced sensors and an onboard Ursa rover for planetary exploration. Let’s see what’s out there!",
          url: "/pledge/ships/rsi-constellation/Constellation-Aquila"
        },
        {
          id: "45",
          afterburner_speed: "910",
          beam: "26.0",
          cargocapacity: "96",
          height: "14.0",
          length: "61.0",
          manufacturer_id: "1",
          mass: "419850",
          max_crew: "4",
          min_crew: "3",
          pitch_max: "25.0",
          production_note: "Damage States being mapped",
          production_status: "flight-ready",
          roll_max: "50.0",
          scm_speed: "190",
          size: "large",
          time_modified: "4 months ago",
          type: "multi",
          xaxis_acceleration: "19.0",
          yaw_max: "25.0",
          yaxis_acceleration: "34.7",
          zaxis_acceleration: "23.3",
          description: "The Constellation Andromeda, a multi-person freighter, is the most popular ship in RSI's current production array. Constellations are beloved by smugglers and merchants alike because they are modular, high powered... and just downright iconic-looking.",
          url: "/pledge/ships/rsi-constellation/Constellation-Andromeda"
        },
        {
          id: "46",
          afterburner_speed: "0",
          beam: "26.0",
          cargocapacity: null,
          height: "14.0",
          length: "61.0",
          manufacturer_id: "1",
          mass: "416009",
          max_crew: "4",
          min_crew: "3",
          pitch_max: null,
          production_note: "Damage States being mapped",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "10 months ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Enjoy the adventure of a multi-crew Constellation on a budget! The Constellation Taurus is a dedicated freighter. Fully configurable but without all the bells-and-whistles, the Taurus is a great way to get started with crewed ships.",
          url: "/pledge/ships/rsi-constellation/Constellation-Taurus"
        },
        {
          id: "49",
          afterburner_speed: "0",
          beam: "26.0",
          cargocapacity: null,
          height: "14.0",
          length: "61.0",
          manufacturer_id: "1",
          mass: "417510",
          max_crew: "4",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A dedicated luxury spacecraft for the discerning star captain. The Constellation Phoenix can be operated as an organization command ship and features a luxurious redesigned interior. \n\nThe Phoenix comes with a Lynx rover and a Kruger P-72 Archimedes Fighter",
          url: "/pledge/ships/rsi-constellation/Constellation-Phoenix"
        },
        {
          id: "156",
          afterburner_speed: "0",
          beam: "26.0",
          cargocapacity: null,
          height: "14.0",
          length: "61.0",
          manufacturer_id: "1",
          mass: "417510",
          max_crew: "4",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "1 year ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Whether you are a discerning socialite or a freewheeling party animal, the Constellation Phoenix Emerald is your personal passport to entertainment. With a swank interior cabin designed specifically for revelry, and a limited edition \"lucky\" paint job, the Emerald is the perfect venue to sip a glass of Radegast Gold or throw back a green Sleeping Tiger Malt while hurtling luxuriously through the stars. Just be sure to bring a designated pilot. The Phoenix Emerald comes with a Lynx rover and a Kruger P-72 Archimedes Fighter.",
          url: "/pledge/ships/rsi-constellation/Constellation-Phoenix-Emerald"
        },
        {
          id: "16",
          afterburner_speed: "1005",
          beam: "23.5",
          cargocapacity: "66",
          height: "9.5",
          length: "38.0",
          manufacturer_id: "4",
          mass: "209230",
          max_crew: "4",
          min_crew: "2",
          pitch_max: "65.0",
          production_note: "This ship is in game and ready to fly immediately.",
          production_status: "flight-ready",
          roll_max: "90.0",
          scm_speed: "205",
          size: "medium",
          time_modified: "3 months ago",
          type: "transport",
          xaxis_acceleration: "40.3",
          yaw_max: "60.0",
          yaxis_acceleration: "49.5",
          zaxis_acceleration: "37.6",
          description: "Freelancers are used as long haul merchant ships by major corporations, but they are just as frequently repurposed as dedicated exploration vessels by independent captains who want to operate on the fringes of the galaxy.",
          url: "/pledge/ships/misc-freelancer/Freelancer"
        },
        {
          id: "31",
          afterburner_speed: "0",
          beam: "23.5",
          cargocapacity: "28",
          height: "9.5",
          length: "38.0",
          manufacturer_id: "4",
          mass: "213680",
          max_crew: "4",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "medium",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Freelancer DUR variant specializes in exploration. Sacrificing some of the cargo capacity of the standard Freelancer for an enhanced jump drive, a more advanced scanner, and an expanded fuel tank may seem like a bad call to some, but those who value discovery over profit will find it to be their ship of choice.",
          url: "/pledge/ships/misc-freelancer/Freelancer-DUR"
        },
        {
          id: "32",
          afterburner_speed: "0",
          beam: "36.0",
          cargocapacity: "122",
          height: "9.5",
          length: "38.0",
          manufacturer_id: "4",
          mass: "336230",
          max_crew: "4",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "medium",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Freelancer MAX variant is for those who prize increased cargo capacity over everything else. Combine that additional storage with MISC’s unrivaled dependability and reputation, and you can see why the MAX is the preferred transport for many independent haulers in Empire today.",
          url: "/pledge/ships/misc-freelancer/Freelancer-MAX"
        },
        {
          id: "33",
          afterburner_speed: "0",
          beam: "23.5",
          cargocapacity: "28",
          height: "9.5",
          length: "38.0",
          manufacturer_id: "4",
          mass: "213680",
          max_crew: "4",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "medium",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Freelancer MIS is a limited edition militarized variant of the classic mercantile ship developed by the UEE. These were produced in very small quantity due to some early payload incidents. This version sacrifices the majority of the cargo capacity to make way for missiles. ",
          url: "/pledge/ships/misc-freelancer/Freelancer-MIS"
        },
        {
          id: "56",
          afterburner_speed: "1115",
          beam: "26.5",
          cargocapacity: "46",
          height: "10.0",
          length: "29.0",
          manufacturer_id: "5",
          mass: "226700",
          max_crew: "2",
          min_crew: "2",
          pitch_max: "85.0",
          production_note: "Update pass in progress.",
          production_status: "flight-ready",
          roll_max: "110.0",
          scm_speed: "220",
          size: "medium",
          time_modified: "4 months ago",
          type: "multi",
          xaxis_acceleration: "49.4",
          yaw_max: "90.0",
          yaxis_acceleration: "50.4",
          zaxis_acceleration: "49.6",
          description: "Drake Interplanetary claims that the Cutlass Black is a low-cost, easy-to-maintain solution for local in-system militia units. The larger-than-average cargo hold, RIO seat and dedicated tractor mount are, the company literature insists, for facilitating search and rescue operations.",
          url: "/pledge/ships/drake-cutlass/Cutlass-Black"
        },
        {
          id: "57",
          afterburner_speed: "0",
          beam: "26.0",
          cargocapacity: "12",
          height: "14.0",
          length: "36.0",
          manufacturer_id: "5",
          mass: "226700",
          max_crew: "2",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "183",
          size: "medium",
          time_modified: "3 months ago",
          type: "support",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Is there a doctor in the house? The Cutlass Red converts the standard cargo hold to a well-equipped medical facility including two Medical Beds. This star bound ambulance features the Nav-E7 Long Range Scanner, and Secure Plus Docking Collar making it ideal for search and rescue.  This model contains emergency light-bars and a red emergency themed paint job for easy identification. ",
          url: "/pledge/ships/drake-cutlass/Cutlass-Red"
        },
        {
          id: "58",
          afterburner_speed: "1210",
          beam: "26.0",
          cargocapacity: "12",
          height: "14.0",
          length: "36.0",
          manufacturer_id: "5",
          mass: "226700",
          max_crew: "3",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "198",
          size: "medium",
          time_modified: "1 month ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Sleek, mean, and royal. The Cutlass Blue adds missiles, a more aggressive engine, and Durasteel holding cells in the cargo bay to the standard model. The Cutlass Blue is the outworld militia standard ship of choice for patrols.",
          url: "/pledge/ships/drake-cutlass/Cutlass-Blue"
        },
        {
          id: "193",
          afterburner_speed: "1115",
          beam: "26.5",
          cargocapacity: "46",
          height: "10.0",
          length: "29.0",
          manufacturer_id: "5",
          mass: "226700",
          max_crew: "2",
          min_crew: "2",
          pitch_max: "85.0",
          production_note: "Update pass in progress.",
          production_status: "flight-ready",
          roll_max: "110.0",
          scm_speed: "220",
          size: "medium",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "49.4",
          yaw_max: "90.0",
          yaxis_acceleration: "50.4",
          zaxis_acceleration: "49.6",
          description: "Drake Interplanetary claims that the Cutlass Black is a low-cost, easy-to-maintain solution for local in-system militia units. The larger-than-average cargo hold, RIO seat and dedicated tractor mount are, the company literature insists, for facilitating search and rescue operations.",
          url: "/pledge/ships/drake-cutlass/Cutlass-Black-Best-In-Show-Edition"
        },
        {
          id: "100",
          afterburner_speed: "1310",
          beam: "16.5",
          cargocapacity: "0",
          height: "5.5",
          length: "22.5",
          manufacturer_id: "12",
          mass: "50040",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "105.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "145.0",
          scm_speed: "250",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "66.2",
          yaw_max: "105.0",
          yaxis_acceleration: "85.6",
          zaxis_acceleration: "70.5",
          description: "Initially designed as a frontline carrier for the military, the Avenger Stalker took a different path, ultimately having a long and storied career as the standard patrol craft of the UEE Advocacy. Utilizing its cargo hold for prisoner transport, the Avenger features a sturdy, reliable hull and the capacity for larger-than-expected engine mounts. *This is the standard Avenger chassis with the Stalker Prisoner Transport module pre-installed.*",
          url: "/pledge/ships/aegis-avenger/Avenger-Stalker"
        },
        {
          id: "124",
          afterburner_speed: "1115",
          beam: "16.5",
          cargocapacity: "8",
          height: "5.5",
          length: "22.5",
          manufacturer_id: "12",
          mass: "50735",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "80.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "90.0",
          scm_speed: "205",
          size: "small",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: "67.6",
          yaw_max: "80.0",
          yaxis_acceleration: "89.0",
          zaxis_acceleration: "71.5",
          description: "Created as part of the ‘Masters of Flight’ series in conjunction with the flight-sim Arena Commander, the Renegade pays tribute to famed pilot Danny Solomon for his notable work with the Advocacy to bring justice to Bremen. This Avenger Titan comes equipped with a specialized dogfighting-focused loadout and a special-edition livery honoring this iconic ship.\n",
          url: "/pledge/ships/aegis-avenger/Avenger-Titan-Renegade"
        },
        {
          id: "101",
          afterburner_speed: "1305",
          beam: "16.5",
          cargocapacity: "0",
          height: "5.5",
          length: "22.5",
          manufacturer_id: "12",
          mass: "50070",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "105.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "145.0",
          scm_speed: "240",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "65.4",
          yaw_max: "105.0",
          yaxis_acceleration: "83.4",
          zaxis_acceleration: "69.5",
          description: "Outfitted with a Behring REP-8 EMP Generator, the Warlock makes non-lethal suppression possible via a powerful electromagnetic wave capable of disabling any electronics within the blast radius.\n\n*This is the standard Avenger chassis with the Warlock EMP module pre-installed.*",
          url: "/pledge/ships/aegis-avenger/Avenger-Warlock"
        },
        {
          id: "102",
          afterburner_speed: "1115",
          beam: "16.5",
          cargocapacity: "8",
          height: "5.5",
          length: "22.5",
          manufacturer_id: "12",
          mass: "50056",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "105.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "145.0",
          scm_speed: "260",
          size: "small",
          time_modified: "3 weeks ago",
          type: "transport",
          xaxis_acceleration: "67.6",
          yaw_max: "105.0",
          yaxis_acceleration: "89.0",
          zaxis_acceleration: "71.5",
          description: "Lacking the prisoner cells of the Stalker or the EMP of the Warlock, the Titan’s hold is free to carry cargo. Couple that with the Avenger’s tried and true combat abilities and you’ve got a light cargo hauler that’s more than capable of handling itself in a fight.",
          url: "/pledge/ships/aegis-avenger/Avenger-Titan"
        },
        {
          id: "64",
          afterburner_speed: "980",
          beam: "22.5",
          cargocapacity: "0",
          height: "6.0",
          length: "22.5",
          manufacturer_id: "3",
          mass: "87497",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "80.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "115.0",
          scm_speed: "200",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "52.6",
          yaw_max: "80.0",
          yaxis_acceleration: "59.1",
          zaxis_acceleration: "49.0",
          description: "The civilian model of the Gladiator appeals to those that want explore the ‘Verse with a bit of added security. Supporting a maximum of two, the Gladiator is perfectly equipped to explore and fight with or without a wingman. The Civilian model allows pilots to choose between an extra cargo hold or a bomb bay.",
          url: "/pledge/ships/anvil-gladiator/Gladiator"
        },
        {
          id: "22",
          afterburner_speed: "1345",
          beam: "10.0",
          cargocapacity: "0",
          height: "3.0",
          length: "11.0",
          manufacturer_id: "6",
          mass: "10580",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "130.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "175.0",
          scm_speed: "330",
          size: "small",
          time_modified: "3 months ago",
          type: "competition",
          xaxis_acceleration: "99.7",
          yaw_max: "130.0",
          yaxis_acceleration: "152.1",
          zaxis_acceleration: "114.4",
          description: "If you want to get from point A to point B as quickly as possible and with as much style as possible then ORIGIN's M50 is for you. Featuring supercharged engines that counter a tiny weapons loadout, the M50 is a ship for going FAST.",
          url: "/pledge/ships/origin-m50/M50"
        },
        {
          id: "88",
          afterburner_speed: "890",
          beam: "46.5",
          cargocapacity: "295",
          height: "23.5",
          length: "101.0",
          manufacturer_id: "4",
          mass: "3510025",
          max_crew: "6",
          min_crew: "4",
          pitch_max: "20.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "115",
          size: "large",
          time_modified: "3 months ago",
          type: "support",
          xaxis_acceleration: "8.2",
          yaw_max: "20.0",
          yaxis_acceleration: "8.8",
          zaxis_acceleration: "8.4",
          description: "The Starfarer differs from traditional bulk freighters in one key way: it is a dedicated fuel platform. The Starfarer is designed not only to load, store and protect fuel stasis units, it is designed to take in spaceborne gases and refine them for use without landing. And while it excels at this, the Starfarer can also be used to ferry traditional bulk cargo pods. The listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the extra space available from the bulk cargo pods.",
          url: "/pledge/ships/misc-starfarer/Starfarer"
        },
        {
          id: "89",
          afterburner_speed: "890",
          beam: "46.5",
          cargocapacity: "295",
          height: "23.5",
          length: "101.0",
          manufacturer_id: "4",
          mass: "3517864",
          max_crew: "6",
          min_crew: "4",
          pitch_max: "20.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "120",
          size: "large",
          time_modified: "4 months ago",
          type: "support",
          xaxis_acceleration: "9.0",
          yaw_max: "20.0",
          yaxis_acceleration: "10.0",
          zaxis_acceleration: "9.4",
          description: "The UEE military uses an adapted ‘rough and tumble’ Gemini variant of the Starfarer for their front-line operations, trading some cargo capacity and maneuverability for reinforced armor, increased shielding, more powerful engines and stronger manned turrets. The Gemini also includes an optional missile pod, which can be swapped for the fuel intake unit on either Starfarer variant’s nose. The listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the extra space available from the bulk cargo pods.",
          url: "/pledge/ships/misc-starfarer/Starfarer-Gemini"
        },
      ]);
    });
};
