
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('ship_specs2')
  .truncate()
    .then(function () {
      // Inserts seed entries
      return knex('ship_specs2').insert([
        {
          id: "89",
          afterburner_speed: "890",
          beam: "46.5",
          cargocapacity: "295",
          height: "23.5",
          length: "101.0",
          manufacturer_id: "4",
          mass: "3517864",
          max_crew: "6",
          min_crew: "4",
          pitch_max: "20.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "120",
          size: "large",
          time_modified: "4 months ago",
          type: "support",
          xaxis_acceleration: "9.0",
          yaw_max: "20.0",
          yaxis_acceleration: "10.0",
          zaxis_acceleration: "9.4",
          description: "The UEE military uses an adapted ‘rough and tumble’ Gemini variant of the Starfarer for their front-line operations, trading some cargo capacity and maneuverability for reinforced armor, increased shielding, more powerful engines and stronger manned turrets. The Gemini also includes an optional missile pod, which can be swapped for the fuel intake unit on either Starfarer variant’s nose. The listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the extra space available from the bulk cargo pods.",
          url: "/pledge/ships/misc-starfarer/Starfarer-Gemini"
        },
        {
          id: "24",
          afterburner_speed: "890",
          beam: "39.0",
          cargocapacity: "576",
          height: "13.5",
          length: "111.5",
          manufacturer_id: "5",
          mass: "1608205",
          max_crew: "4",
          min_crew: "2",
          pitch_max: "20.0",
          production_note: "Hull concept complete",
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "130",
          size: "large",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "11.7",
          yaw_max: "20.0",
          yaxis_acceleration: "12.8",
          zaxis_acceleration: "9.9",
          description: "First introduced in 2871, Drake Interplanetary’s Caterpillar has long proven to be a reliable, cost-effective multi-role vessel, capable of being outfitted for everything from mercantile operations to combat support. Long hailed as a hard-fought alternative to the ubiquitous Hull series, the Caterpillar is a freighter that doesn’t skimp on weaponry or customization.",
          url: "/pledge/ships/drake-caterpillar/Caterpillar"
        },
        {
          id: "125",
          afterburner_speed: "890",
          beam: "39.0",
          cargocapacity: "576",
          height: "13.5",
          length: "111.5",
          manufacturer_id: "5",
          mass: "1608205",
          max_crew: "4",
          min_crew: "2",
          pitch_max: "20.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "130",
          size: "large",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "11.7",
          yaw_max: "20.0",
          yaxis_acceleration: "12.8",
          zaxis_acceleration: "9.9",
          description: "Drake maintains that the Caterpillar, a sprawling, modular spacecraft which appears at least somewhat like its namesake, is for legitimate commerce and extended search and rescue missions... but this special livery seems to suggest otherwise.",
          url: "/pledge/ships/drake-caterpillar/Caterpillar-Pirate-Edition"
        },
        {
          id: "194",
          afterburner_speed: "890",
          beam: "39.0",
          cargocapacity: "576",
          height: "13.5",
          length: "111.5",
          manufacturer_id: "5",
          mass: "1608205",
          max_crew: "4",
          min_crew: "2",
          pitch_max: "20.0",
          production_note: "Hull concept complete",
          production_status: "flight-ready",
          roll_max: "35.0",
          scm_speed: "130",
          size: "large",
          time_modified: "4 months ago",
          type: "transport",
          xaxis_acceleration: "11.7",
          yaw_max: "20.0",
          yaxis_acceleration: "12.8",
          zaxis_acceleration: "9.9",
          description: "First introduced in 2871, Drake Interplanetary’s Caterpillar has long proven to be a reliable, cost-effective multi-role vessel, capable of being outfitted for everything from mercantile operations to combat support. Long hailed as a hard-fought alternative to the ubiquitous Hull series, the Caterpillar is a freighter that doesn’t skimp on weaponry or customization.",
          url: "/pledge/ships/drake-caterpillar/Caterpillar-Best-In-Show-Edition"
        },
        {
          id: "72",
          afterburner_speed: "814",
          beam: "42.5",
          cargocapacity: "0",
          height: "12.5",
          length: "69.5",
          manufacturer_id: "12",
          mass: "300392",
          max_crew: "7",
          min_crew: "4",
          pitch_max: "20.0",
          production_note: "This ship is in game and ready to fly immediately.",
          production_status: "flight-ready",
          roll_max: "30.0",
          scm_speed: "145",
          size: "large",
          time_modified: "6 months ago",
          type: "combat",
          xaxis_acceleration: "22.9",
          yaw_max: "20.0",
          yaxis_acceleration: "33.4",
          zaxis_acceleration: "18.9",
          description: "The Aegis Dynamics’ Retaliator has landed! One of the United Empire of Earth’s most powerful warbirds, the Retaliator was designed as a fearsome weapons platform designed to strike and kill capital ships. A key portion of the UEE’s power projection, Retaliator squadrons have served with distinction against outlaws, the Vanduul and elsewhere. This version of the Retaliator includes the bomb bay and torpedo launcher.",
          url: "/pledge/ships/aegis-retaliator/Retaliator-Bomber"
        },
        {
          id: "99",
          afterburner_speed: "815",
          beam: "42.5",
          cargocapacity: "0",
          height: "12.5",
          length: "69.5",
          manufacturer_id: "12",
          mass: "300392",
          max_crew: "7",
          min_crew: "4",
          pitch_max: "25.0",
          production_note: "Concept complete. Current owners receive Retaliator Bomber as loaner.",
          production_status: "in-concept",
          roll_max: "50.0",
          scm_speed: "185",
          size: "large",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "22.9",
          yaw_max: "25.0",
          yaxis_acceleration: "33.4",
          zaxis_acceleration: "18.8",
          description: "The Aegis Dynamics’ Retaliator has landed! One of the United Empire of Earth’s most powerful warbirds, the Retaliator was designed as a fearsome weapons platform designed to strike and kill capital ships. A key portion of the UEE’s power projection, Retaliator squadrons have served with distinction against outlaws, the Vanduul and elsewhere. The base version of the Retaliator is customizable with additional modules to fit your needs.",
          url: "/pledge/ships/aegis-retaliator/Retaliator-Base"
        },
        {
          id: "26",
          afterburner_speed: "1240",
          beam: "23.0",
          cargocapacity: "0",
          height: "8.5",
          length: "31.0",
          manufacturer_id: "13",
          mass: "59573",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "105.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "285",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "85.5",
          yaw_max: "105.0",
          yaxis_acceleration: "106.7",
          zaxis_acceleration: "91.6",
          description: "Fast becoming the symbol of the Vanduul Race, the Scythe is the foot soldier in every raid and the target of every human fighter pilot. Featuring a hefty weapons payload, the Scythe's real asset is its maneuverability, found in the twin main and twelve manuevering thrusters.",
          url: "/pledge/ships/scythe/Scythe"
        },
        {
          id: "27",
          afterburner_speed: "0",
          beam: "126.0",
          cargocapacity: "831",
          height: "46.0",
          length: "242.0",
          manufacturer_id: "12",
          mass: "37459548",
          max_crew: "28",
          min_crew: "8",
          pitch_max: null,
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "3 years ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: "0.0",
          description: "Larger than a bomber but smaller than a ship of the line, frigates occupy an interesting space in the pantheon of warships. While they lack the heavy armor and the capital weaponry of a cruiser, frigates are more maneuverable and are highly configurable.",
          url: "/pledge/ships/aegis-idris/Idris-M"
        },
        {
          id: "28",
          afterburner_speed: "0",
          beam: "126.0",
          cargocapacity: "995",
          height: "46.0",
          length: "233.0",
          manufacturer_id: "12",
          mass: "37310200",
          max_crew: "28",
          min_crew: "8",
          pitch_max: null,
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "3 years ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: "0.0",
          description: "A mark two \"peacekeeper\" variant developed for the UEE patrol services, the Idris-P strips the standard ship's ship-to-ship gun and spinal mount in favor of additional cargo capacity and superior speed.",
          url: "/pledge/ships/aegis-idris/Idris-P"
        },
        {
          id: "92",
          afterburner_speed: "1030",
          beam: "7.7",
          cargocapacity: "0",
          height: "2.2",
          length: "12.0",
          manufacturer_id: "19",
          mass: "8493",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "128.0",
          scm_speed: "270",
          size: "snub",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "70.3",
          yaw_max: "90.0",
          yaxis_acceleration: "82.7",
          zaxis_acceleration: "61.6",
          description: "Originally designed to pair with the RSI Constellation, the P-52 Merlin is now available to all pilots! A dedicated parasite fighter, the Merlin is designed to be transported from place to place aboard a larger ship. Boasting a centerline Gatling cannon and a Lightning Power engine, the Merlin is a fast, maneuverable ship that packs a surprising punch! Ideal for racing, local reconnaissance and fast combat.",
          url: "/pledge/ships/p52-merlin/P-52-Merlin"
        },
        {
          id: "65",
          afterburner_speed: "1160",
          beam: "18.0",
          cargocapacity: "6",
          height: "9.0",
          length: "21.5",
          manufacturer_id: "22",
          mass: "32970",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "255",
          size: "small",
          time_modified: "4 months ago",
          type: "multi",
          xaxis_acceleration: "73.8",
          yaw_max: "90.0",
          yaxis_acceleration: "84.1",
          zaxis_acceleration: "72.2",
          description: "Inspired by Consolidated Outland CEO Silas Koerner’s cutting edge vision, the Mustang Alpha is a sleek, stylish spacecraft that uses ultralight alloys to push power ratios to the limits, albeit sometimes unsafely. And now, with the optional Cargo Carrier, you can have the Alpha’s advantages without sacrificing carrying capacity.",
          url: "/pledge/ships/mustang/Mustang-Alpha"
        },
        {
          id: "66",
          afterburner_speed: "1215",
          beam: "18.0",
          cargocapacity: "0",
          height: "9.0",
          length: "21.5",
          manufacturer_id: "22",
          mass: "39610",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "250",
          size: "small",
          time_modified: "3 months ago",
          type: "exploration",
          xaxis_acceleration: "70.7",
          yaw_max: "90.0",
          yaxis_acceleration: "82.0",
          zaxis_acceleration: "69.0",
          description: "The Mustang Beta, with its unprecedented range, is made for long duration flights. The factory standard Tarsus Leaper Jump Engine enables the Beta to travel to the galaxy’s farthest systems with ease, while the ship’s unique Com4T living quarters will make the journey feel like you never left home.",
          url: "/pledge/ships/mustang/Mustang-Beta"
        },
        {
          id: "67",
          afterburner_speed: "1340",
          beam: "18.0",
          cargocapacity: "0",
          height: "9.0",
          length: "21.5",
          manufacturer_id: "22",
          mass: "30263",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "110.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "168.0",
          scm_speed: "325",
          size: "small",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "93.3",
          yaw_max: "110.0",
          yaxis_acceleration: "136.1",
          zaxis_acceleration: "105.6",
          description: "Consolidated Outland’s design and engineering teams have managed to tweak and refine the Mustang into an admirable racer. The end result, the Mustang Gamma, has smooth acceleration, and power on demand thanks to an innovative package featuring three powerful Magma Jet engines for maximum thrust.",
          url: "/pledge/ships/mustang/Mustang-Gamma"
        },
        {
          id: "69",
          afterburner_speed: "1225",
          beam: "18.0",
          cargocapacity: "0",
          height: "9.0",
          length: "21.5",
          manufacturer_id: "22",
          mass: "37345",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "240",
          size: "small",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "73.3",
          yaw_max: "90.0",
          yaxis_acceleration: "87.7",
          zaxis_acceleration: "69.3",
          description: "While it may not be able to go toe to toe with some of the military specific ships, by reinforcing the Mustang’s already strong hull construction with Consolidated Outland’s own line of Cavalry Class Mass Reduction Armor, the Delta has a reduced cross-sectional signature that evens the playing field.",
          url: "/pledge/ships/mustang/Mustang-Delta"
        },
        {
          id: "70",
          afterburner_speed: "1340",
          beam: "15.5",
          cargocapacity: "0",
          height: "5.5",
          length: "17.5",
          manufacturer_id: "22",
          mass: "30263",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "110.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "168.0",
          scm_speed: "325",
          size: "small",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "93.3",
          yaw_max: "110.0",
          yaxis_acceleration: "136.1",
          zaxis_acceleration: "105.6",
          description: "Consolidated Outland teamed up with custom tuning company Accelerated Mass Design to create a limited edition racer that features a ramped up fuel intake for faster recycling of the ship’s already impressive boost system. To cap off the collaboration, AMD enlisted resident underground artist Sektor8 to design the dynamic paint job.",
          url: "/pledge/ships/mustang/Mustang-Omega"
        },
        {
          id: "172",
          afterburner_speed: "1160",
          beam: "15.5",
          cargocapacity: "6",
          height: "5.5",
          length: "17.5",
          manufacturer_id: "22",
          mass: "32970",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "255",
          size: "small",
          time_modified: "1 year ago",
          type: "multi",
          xaxis_acceleration: "73.8",
          yaw_max: "90.0",
          yaxis_acceleration: "84.1",
          zaxis_acceleration: "72.2",
          description: "Make the ultimate statement and show the universe that you are a paragon of style and a bulwark of freedom. With this limited Vindicator Edition livery, the maverick designers at Consolidated Outland have pulled out all the stops, creating a trim package that commemorates CitizenCon 2948 and embodies the spirit of daring that defines both the original vision of Silas Koerner and the unyielding determination of the UEE.",
          url: "/pledge/ships/mustang/Mustang-Alpha-Vindicator"
        },
        {
          id: "59",
          afterburner_speed: "0",
          beam: "19.5",
          cargocapacity: "0",
          height: "11.0",
          length: "37.5",
          manufacturer_id: "12",
          mass: "120380",
          max_crew: "5",
          min_crew: "3",
          pitch_max: null,
          production_note: "Waiting for resources to start modeling",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "medium",
          time_modified: "10 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: "0.0",
          description: "Now you can own the Next Great Starship! Designed by Star Citizen's backers, the Aegis Redeemer is a powerful fighting ship capable of holding its own in combat with a powerful weapons payload. Dotted with turrets and missiles, the Redeemer also doubles as an armored landing craft capable of delivering armored soldiers for first person combat!",
          url: "/pledge/ships/redeemer/Redeemer"
        },
        {
          id: "60",
          afterburner_speed: "1235",
          beam: "17.0",
          cargocapacity: "0",
          height: "5.5",
          length: "20.0",
          manufacturer_id: "12",
          mass: "48958",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "120.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "160.0",
          scm_speed: "280",
          size: "small",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: "88.6",
          yaw_max: "120.0",
          yaxis_acceleration: "118.5",
          zaxis_acceleration: "92.1",
          description: "The Gladius is an older design which has been updated over the years to keep up with modern technology. In military circles, the Gladius is beloved for its performance and its simplicity. A fast, light fighter with a laser-focus on dogfighting, the Gladius is an ideal interceptor or escort ship.",
          url: "/pledge/ships/gladius/Gladius"
        },
        {
          id: "121",
          afterburner_speed: "1236",
          beam: "17.0",
          cargocapacity: "0",
          height: "5.5",
          length: "20.0",
          manufacturer_id: "12",
          mass: "48958",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "100.0",
          scm_speed: "220",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "88.6",
          yaw_max: "90.0",
          yaxis_acceleration: "118.5",
          zaxis_acceleration: "92.1",
          description: "Created as part of the ‘Masters of Flight’ series in conjunction with the flight-sim Arena Commander, the Valiant pays tribute to famed defense pilot Condi Hillard for being the first Human on record to defeat a Vanduul in combat. This Gladius comes equipped with a specialized dogfighting focused loadout and a custom special edition livery honoring her iconic ship.\n",
          url: "/pledge/ships/gladius/Gladius-Valiant"
        },
        {
          id: "188",
          afterburner_speed: "1235",
          beam: "17.0",
          cargocapacity: "0",
          height: "5.5",
          length: "20.0",
          manufacturer_id: "12",
          mass: "48958",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "120.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "160.0",
          scm_speed: "280",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "88.6",
          yaw_max: "120.0",
          yaxis_acceleration: "118.5",
          zaxis_acceleration: "92.1",
          description: null,
          url: "/pledge/ships/gladius/Pirate-Gladius"
        },
        {
          id: "35",
          afterburner_speed: "1325",
          beam: "13.0",
          cargocapacity: "0",
          height: "8.0",
          length: "30.5",
          manufacturer_id: "81",
          mass: "67115",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "125.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "160.0",
          scm_speed: "300",
          size: "small",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: "104.5",
          yaw_max: "125.0",
          yaxis_acceleration: "107.3",
          zaxis_acceleration: "104.5",
          description: "The Xi'an Aopoa corporation manufactures an export model of the Qhire Khartu, the Khartu-al, for sale to Human civilians. The export model features the same Xi'an maneuvering rig, but control surfaces modified for Human use and a more limited armament.",
          url: "/pledge/ships/khartu/Khartu-Al"
        },
        {
          id: "36",
          afterburner_speed: "0",
          beam: "160.0",
          cargocapacity: "3584",
          height: "65.0",
          length: "160.0",
          manufacturer_id: "21",
          mass: "9635000",
          max_crew: "8",
          min_crew: "4",
          pitch_max: null,
          production_note: "Hull concept complete",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "3 months ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Banu traders are renowned for their merchant prowess, traveling the spacelanes and trading with everyone from humans to the Vanduul! Their sturdy, dedicated trading ships are prized beyond all other transports, sometimes passing from generation to generation of Banu.",
          url: "/pledge/ships/merchantman/Merchantman"
        },
        {
          id: "55",
          afterburner_speed: "0",
          beam: "52.0",
          cargocapacity: "1600",
          height: "24.0",
          length: "123.0",
          manufacturer_id: "6",
          mass: "4590000",
          max_crew: "5",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "2 weeks ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With an elegant, sleek exterior that belies its spacious interior, the 890 Jump is a true engineering marvel; crafted to impress from every angle by combining a unique, innovative design with the finest materials and the most advanced technology. The result is a vessel that is in a class all of its own, a masterpiece worthy of the name ORIGIN.",
          url: "/pledge/ships/890-jump/890-Jump"
        },
        {
          id: "62",
          afterburner_speed: "0",
          beam: "76.5",
          cargocapacity: "456",
          height: "30.0",
          length: "126.5",
          manufacturer_id: "3",
          mass: "4397858",
          max_crew: "6",
          min_crew: "4",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "1076",
          size: "large",
          time_modified: "3 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Anvil Carrack features reinforced fuel tanks for long-duration flight, an advanced jump drive, and a dedicated computer core for jump charting operations. Originally a military exclusive, the Carrack is now available for civilian use. On-board accommodations include crew medical and repair facilities, and a mapping-oriented sensor suite.",
          url: "/pledge/ships/carrack/Carrack"
        },
        {
          id: "204",
          afterburner_speed: "0",
          beam: "76.5",
          cargocapacity: "456",
          height: "30.0",
          length: "126.5",
          manufacturer_id: "3",
          mass: "4397858",
          max_crew: "6",
          min_crew: "4",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "1076",
          size: "large",
          time_modified: "3 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Anvil Carrack features reinforced fuel tanks for long-duration flight, an advanced jump drive, and a dedicated computer core for jump charting operations. Originally a military exclusive, the Carrack is now available for civilian use. On-board accommodations include crew medical and repair facilities, and a mapping-oriented sensor suite.",
          url: "/pledge/ships/carrack/Carrack-W-C8X"
        },
        {
          id: "205",
          afterburner_speed: "0",
          beam: "76.5",
          cargocapacity: "456",
          height: "30.0",
          length: "126.5",
          manufacturer_id: "3",
          mass: "4397858",
          max_crew: "6",
          min_crew: "4",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "1076",
          size: "large",
          time_modified: "3 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Anvil Carrack features reinforced fuel tanks for long-duration flight, an advanced jump drive, and a dedicated computer core for jump charting operations. Originally a military exclusive, the Carrack is now available for civilian use. On-board accommodations include crew medical and repair facilities, and a mapping-oriented sensor suite.",
          url: "/pledge/ships/carrack/Carrack-Expedition-W-C8X"
        },
        {
          id: "206",
          afterburner_speed: "0",
          beam: "76.5",
          cargocapacity: "456",
          height: "30.0",
          length: "126.5",
          manufacturer_id: "3",
          mass: "4397858",
          max_crew: "6",
          min_crew: "4",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "1076",
          size: "large",
          time_modified: "3 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Anvil Carrack features reinforced fuel tanks for long-duration flight, an advanced jump drive, and a dedicated computer core for jump charting operations. Originally a military exclusive, the Carrack is now available for civilian use. On-board accommodations include crew medical and repair facilities, and a mapping-oriented sensor suite.",
          url: "/pledge/ships/carrack/Carrack-Expedition"
        },
        {
          id: "61",
          afterburner_speed: "1360",
          beam: "12.5",
          cargocapacity: "0",
          height: "9.0",
          length: "23.5",
          manufacturer_id: "5",
          mass: "66031",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "50.0",
          production_note: "This ship is in game and ready to fly immediately.",
          production_status: "flight-ready",
          roll_max: "65.0",
          scm_speed: "235",
          size: "small",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: "56.1",
          yaw_max: "50.0",
          yaxis_acceleration: "126.5",
          zaxis_acceleration: "50.9",
          description: "The Drake Herald is a small, armored ship designed to safely get information from Point A to Point B. Featuring a powerful central engine (for high speed transit and generating the power needed for effective data encryption/containment), advanced encryption software and an armored computer core, the Herald is unique among personal spacecraft in that it is designed to be easily ‘cleaned’ when in danger of capture.",
          url: "/pledge/ships/herald/Herald"
        },
        {
          id: "41",
          afterburner_speed: "0",
          beam: "55.0",
          cargocapacity: "4608",
          height: "55.0",
          length: "125.0",
          manufacturer_id: "4",
          mass: "886930",
          max_crew: "4",
          min_crew: "2",
          pitch_max: null,
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Often called the most common ship in the galaxy, the Hull C is the most-produced of the range and is considered by many to be the most versatile. Intended to hit the ‘sweet spot’ between the smaller single-person transports and the massive superfreighters that make up the rest of the range, the Hull C offers the expansive modularity of the larger ships while still retaining a modicum of the maneuverability allowed the low end of the range.",
          url: "/pledge/ships/hull/Hull-C"
        },
        {
          id: "84",
          afterburner_speed: "0",
          beam: "8.0",
          cargocapacity: "48",
          height: "4.0",
          length: "22.0",
          manufacturer_id: "4",
          mass: "122650",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "small",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The smallest, most affordable Hull. The Hull A is great for those just striking out in the galaxy on their own. The Hull A is most similar to the Aurora and Mustang, but lacks the ‘jack of all trades’ nature. Where the others trade cargo capacity for firepower or speed, the Hull A is 100% on-mission transport! Additionally, Hull A (and B) are often used as station-to-orbit ferries.",
          url: "/pledge/ships/hull/Hull-A"
        },
        {
          id: "85",
          afterburner_speed: "0",
          beam: "15.5",
          cargocapacity: "384",
          height: "17.0",
          length: "49.0",
          manufacturer_id: "4",
          mass: "387500",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "medium",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Hull B is a more rugged option most often compared to MISC’s own Freelancer. But where the Freelancer is equipped for long range exploration and other roles, the Hull B is a pure cargo transport. Hull B are often used as corporate support ships, and it is not uncommon to spot several in different liveries during a single flight.",
          url: "/pledge/ships/hull/Hull-B"
        },
        {
          id: "86",
          afterburner_speed: "0",
          beam: "70.0",
          cargocapacity: "20736",
          height: "70.0",
          length: "209.0",
          manufacturer_id: "4",
          mass: "1216000",
          max_crew: "5",
          min_crew: "3",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Hull D kicks off the larger end of the spectrum with a massive ship built around a rugged frame. The Hull D is affordable enough to be operated by mid-sized organizations and companies. Hull D are often used as flagships for mercantile operations, but their bulk means that they should be operated with escort fighters while not in safe space. The UEE military uses modified Hull D as part of their supply chain, arming and refueling the soldiers on the front line.",
          url: "/pledge/ships/hull/Hull-D"
        },
        {
          id: "87",
          afterburner_speed: "0",
          beam: "104.0",
          cargocapacity: "98304",
          height: "104.0",
          length: "372.0",
          manufacturer_id: "4",
          mass: "1652000",
          max_crew: "5",
          min_crew: "4",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The largest specialized freighter available on the market today, the Hull E is generally owned by major corporations and operated with a high degree of planning. The lack of maneuverability inherent in such a large ship means that anyone planning to operate them should be careful about equipping turrets and providing escort. Their potential load (and modularity) is unparalleled, however: no other ship allows as much room to store goods or to modify towards another role!",
          url: "/pledge/ships/hull/Hull-E"
        },
        {
          id: "71",
          afterburner_speed: "0",
          beam: "50.0",
          cargocapacity: "384",
          height: "50.0",
          length: "170.0",
          manufacturer_id: "1",
          mass: "26496000",
          max_crew: "7",
          min_crew: "4",
          pitch_max: null,
          production_note: "Hull concept complete",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Roberts Space Industries’ goal has always been to make the stars available to individual Citizens. Now, with the RSI Orion mining platform, RSI is letting individuals take over a process formerly controlled by mega-corporations. The Orion’s features include high-grade turret-mounted tractor beam arrays, plenty of mineral storage and a cabin designed by the team that brought you the Aurora and Constellation!\n\n\nThe listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the mined material capacity in the storage pods which will be detailed later.",
          url: "/pledge/ships/orion/Orion"
        },
        {
          id: "51",
          afterburner_speed: "930",
          beam: "118.0",
          cargocapacity: "180",
          height: "50.0",
          length: "155.0",
          manufacturer_id: "12",
          mass: "9500158",
          max_crew: "5",
          min_crew: "4",
          pitch_max: "15.0",
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "flight-ready",
          roll_max: "30.0",
          scm_speed: "100",
          size: "large",
          time_modified: "3 months ago",
          type: "industrial",
          xaxis_acceleration: "8.2",
          yaw_max: "15.0",
          yaxis_acceleration: "8.4",
          zaxis_acceleration: "8.3",
          description: "The Aegis Reclaimer is an industrial salvage ship. Equipped with a reinforced cargo bay, a long-range jump drive and launch pods for unmanned drones, the Reclaimer is an ideal ship for taking advantage of deep space wrecks. Tractor beams, floodlights, scanner options and docking ports round out the tools on this capable, utilitarian spacecraft.\n\nThe listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the salvaged material capacity which will be detailed later.",
          url: "/pledge/ships/reclaimer/Reclaimer"
        },
        {
          id: "196",
          afterburner_speed: "930",
          beam: "118.0",
          cargocapacity: "180",
          height: "50.0",
          length: "155.0",
          manufacturer_id: "12",
          mass: "9500158",
          max_crew: "5",
          min_crew: "4",
          pitch_max: "15.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "30.0",
          scm_speed: "100",
          size: "large",
          time_modified: "3 months ago",
          type: "industrial",
          xaxis_acceleration: "8.2",
          yaw_max: "15.0",
          yaxis_acceleration: "8.4",
          zaxis_acceleration: "8.3",
          description: "The Aegis Reclaimer is an industrial salvage ship. Equipped with a reinforced cargo bay, a long-range jump drive and launch pods for unmanned drones, the Reclaimer is an ideal ship for taking advantage of deep space wrecks. Tractor beams, floodlights, scanner options and docking ports round out the tools on this capable, utilitarian spacecraft.\n\nThe listed Cargo Capacity is only for the dedicated Cargo Room and does not account for the salvaged material capacity which will be detailed later.",
          url: "/pledge/ships/reclaimer/Reclaimer-Best-In-Show-Edition"
        },
        
      ]);
    });
};
