
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('ship_specs3')
  .truncate()
    .then(function () {
      // Inserts seed entries
      return knex('ship_specs3').insert([
        {
          id: "63",
          afterburner_speed: "0",
          beam: "198.0",
          cargocapacity: "5400",
          height: "72.0",
          length: "480.0",
          manufacturer_id: "12",
          mass: "109860179",
          max_crew: "80",
          min_crew: "12",
          pitch_max: null,
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "3 years ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: "0.0",
          description: "Designed for use by the UEE military, the Javelin is a massive, modular capital ship that can be appropriated for entrepreneurial use. With a detailed interior, plenty of modular room options and a high crew capacity, the Javelin is a ship that has made a name for itself in a variety of roles.",
          url: "/pledge/ships/aegis-javelin/Javelin"
        },
        {
          id: "75",
          afterburner_speed: "1115",
          beam: "40.0",
          cargocapacity: "0",
          height: "8.5",
          length: "38.5",
          manufacturer_id: "12",
          mass: "238616",
          max_crew: "2",
          min_crew: "2",
          pitch_max: "80.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "120.0",
          scm_speed: "225",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: "51.9",
          yaw_max: "80.0",
          yaxis_acceleration: "54.5",
          zaxis_acceleration: "53.3",
          description: "A hard-charging bulldog of a fighter which features extensive forward-mounted weaponry designed to tear through the shields and armor of other spacecraft. So-named because their multiple-jump range allows them to form the vanguard of any military expedition, Vanguards have seen extensive service against the Vanduul.",
          url: "/pledge/ships/vanguard/Vanguard-Warden"
        },
        {
          id: "95",
          afterburner_speed: "0",
          beam: "40.0",
          cargocapacity: "0",
          height: "8.0",
          length: "38.5",
          manufacturer_id: "12",
          mass: "240092",
          max_crew: "2",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "225",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Vanguard Harbinger is Earth’s standard fighter-bomber, converting the standard Warden model’s escape pod into a potent bomb bay. The extended range of the Vanguard and the relatively small profile mean that it can go where carrier-based planes or larger strategic bombers don’t… and then strike hard and make it back to frontier bases. The Vanguard Harbinger is a powerful bomber that can operate out of the roughest forward operating bases.\n",
          url: "/pledge/ships/vanguard/Vanguard-Harbinger"
        },
        {
          id: "96",
          afterburner_speed: "0",
          beam: "40.0",
          cargocapacity: "0",
          height: "8.5",
          length: "38.5",
          manufacturer_id: "12",
          mass: "238616",
          max_crew: "2",
          min_crew: "2",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "225",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Vanguard Sentinel is a ship that’s designed to fight smart instead of taking enemies head on. The conversion features an AR cockpit, an external e-War pod, decoy missiles and a set of EMP charges. Vanguard Sentinels often provide necessary combat support for combined operations. A lone Sentinel assigned wild weasel tasks is frequently paired with Harbinger bombers and Warden escorts for large attack missions.",
          url: "/pledge/ships/vanguard/Vanguard-Sentinel"
        },
        {
          id: "127",
          afterburner_speed: "1020",
          beam: "40.0",
          cargocapacity: "0",
          height: "8.5",
          length: "38.5",
          manufacturer_id: "12",
          mass: "229440",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "80.0",
          production_note: "This ship is in game and ready to fly immediately.",
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "225",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: "51.8",
          yaw_max: "80.0",
          yaxis_acceleration: "54.6",
          zaxis_acceleration: "53.4",
          description: "The Vanguard Hoplite is a cross between the winning Vanguard deep space fighter and a dedicated boarding ship. Adapting the reliable design for amphibious operations, the Hoplite is the perfect tool for inserting an armored strike team with enough firepower to get them out again.",
          url: "/pledge/ships/vanguard/Vanguard-Hoplite"
        },
        {
          id: "90",
          afterburner_speed: "1150",
          beam: "28.5",
          cargocapacity: "6",
          height: "4.0",
          length: "14.5",
          manufacturer_id: "4",
          mass: "38566",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "80.0",
          production_note: "This ship is in game and ready to fly immediately.",
          production_status: "flight-ready",
          roll_max: "115.0",
          scm_speed: "220",
          size: "small",
          time_modified: "4 months ago",
          type: "multi",
          xaxis_acceleration: "64.0",
          yaw_max: "80.0",
          yaxis_acceleration: "71.6",
          zaxis_acceleration: "47.3",
          description: "Small supply runs from a planet's surface to a nearby orbital station have become commonplace. With bigger ships focusing more on the long-haul, the Reliant's standard 'Kore' loadout gives it enough carrying capacity for starting out with smaller runs while complementing MISC's Hull-series as a long-haul support ship.\t",
          url: "/pledge/ships/reliant/Reliant-Kore"
        },
        {
          id: "105",
          afterburner_speed: "1150",
          beam: "28.5",
          cargocapacity: "0",
          height: "4.0",
          length: "14.5",
          manufacturer_id: "4",
          mass: "38566",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "166",
          size: "small",
          time_modified: "2 months ago",
          type: "support",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Empire depends on up-to-the-second information, which is why reporters need to be able to go where the news is happening: wherever, whenever. Enter the Mako, all the flexibility and dependability of a MISC Reliant combined with a state of the art Image Enhancement suite and turret-mounted optics to capture every moment as it happens with the clarity and accuracy that makes headlines. ",
          url: "/pledge/ships/reliant/Reliant-Mako"
        },
        {
          id: "106",
          afterburner_speed: "1150",
          beam: "28.5",
          cargocapacity: "0",
          height: "4.0",
          length: "14.5",
          manufacturer_id: "4",
          mass: "38566",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "166",
          size: "small",
          time_modified: "2 months ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Magellan, Pierce, Croshaw, names that echo through history thanks to their adventurous spirit, a curious nature and a reliable ship. The Reliant Sen is a versatile mobile science platform; outfitted with long range capabilities to take you further, longer, and an advanced sensor suite. Perfect for the aspiring explorer who wants to whisper their name into the halls of history.",
          url: "/pledge/ships/reliant/Reliant-Sen"
        },
        {
          id: "107",
          afterburner_speed: "1150",
          beam: "28.5",
          cargocapacity: "0",
          height: "4.0",
          length: "14.5",
          manufacturer_id: "4",
          mass: "38566",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "166",
          size: "small",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With Humanity ever-expanding through the universe, the need for a versatile lightweight fighter has expanded with it. Easy to maintain with a rugged construction, the Reliant Tana makes for an ideal choice for frontier and outpost defense thanks to its custom high-yield power plant, stronger shields and additional weapon mounts.",
          url: "/pledge/ships/reliant/Reliant-Tana"
        },
        {
          id: "91",
          afterburner_speed: "0",
          beam: "90.0",
          cargocapacity: "300",
          height: "16.0",
          length: "85.0",
          manufacturer_id: "68",
          mass: "3120000",
          max_crew: "8",
          min_crew: "2",
          pitch_max: null,
          production_note: "Waiting for resources to start modeling",
          production_status: "in-production",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Genesis is yet another landmark in Crusader Industries’ proud history of transport designs. This ship utilizes award-winning manufacturing techniques and the highest quality parts to create one thing; a next-generation passenger ship at a price that won’t break your budget. Crusader Industries’ proprietary NeoG engine technology offers some of the most efficient flight for a ship of its size.",
          url: "/pledge/ships/starliner/Genesis-Starliner"
        },
        {
          id: "93",
          afterburner_speed: "1230",
          beam: "31.5",
          cargocapacity: "0",
          height: "8.5",
          length: "31.0",
          manufacturer_id: "69",
          mass: "66013",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "100.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "255",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: "81.4",
          yaw_max: "100.0",
          yaxis_acceleration: "93.0",
          zaxis_acceleration: "76.8",
          description: "The Glaive is a symmetrical version of the Scythe. Generally flown by Vanduul with more combat experience, they are better armed and have two huge blades/wings as opposed to one on the standard Scythe.\n\n\nThis model is a human reproduction created by the manufacturer Esperia.\n",
          url: "/pledge/ships/esperia-glaive/Glaive"
        },
        {
          id: "97",
          afterburner_speed: "0",
          beam: "48.0",
          cargocapacity: "500",
          height: "20.0",
          length: "200.0",
          manufacturer_id: "4",
          mass: "4055000",
          max_crew: "5",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Musashi Industrial &amp; Starflight Concern is proud to present the Endeavor-class research vessel, a fully modular space platform designed to be adapted for a variety of scientific and medical tasks. Initially developed as a floating laboratory, the MISC Endeavor can be outfitted for everything from spatial telescopy to use as mobile hospital.",
          url: "/pledge/ships/misc-endeavor/Endeavor"
        },
        {
          id: "98",
          afterburner_speed: "1235",
          beam: "26.0",
          cargocapacity: "0",
          height: "5.0",
          length: "24.0",
          manufacturer_id: "12",
          mass: "78513",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "110.0",
          production_note: "Flight Ready",
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "275",
          size: "small",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: "81.1",
          yaw_max: "110.0",
          yaxis_acceleration: "94.1",
          zaxis_acceleration: "86.0",
          description: "Part of Aegis Dynamics’ Phase Two of new ship models, the Sabre was designed as a space superiority fighter for those situations where you need to leave a lighter footprint. Designed to be a rapid responder, the Sabre is more than capable of establishing battlefield dominance for any number of combat scenarios.",
          url: "/pledge/ships/sabre/Sabre"
        },
        {
          id: "120",
          afterburner_speed: "1235",
          beam: "26.0",
          cargocapacity: "0",
          height: "5.0",
          length: "24.0",
          manufacturer_id: "12",
          mass: "78513",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "85.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "215",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "81.1",
          yaw_max: "85.0",
          yaxis_acceleration: "94.1",
          zaxis_acceleration: "86.0",
          description: "Created as part of the ‘Masters of Flight’ series in conjunction with the flight-sim Arena Commander, the Comet pays tribute to famed pilot Captain Kamur Dalion for his work with Aegis to usher in a new era of combat ship design. This Sabre comes equipped with a specialized dogfighting focused loadout and a custom special edition livery honoring this iconic ship.\n",
          url: "/pledge/ships/sabre/Sabre-Comet"
        },
        {
          id: "148",
          afterburner_speed: "1235",
          beam: "20.5",
          cargocapacity: "0",
          height: "5.0",
          length: "24.0",
          manufacturer_id: "12",
          mass: "69433",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "110.0",
          production_note: "Available in 3.0 patch.",
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "275",
          size: "small",
          time_modified: "3 years ago",
          type: "combat",
          xaxis_acceleration: "82.3",
          yaw_max: "110.0",
          yaxis_acceleration: "95.0",
          zaxis_acceleration: "86.7",
          description: "Part of Aegis Dynamics’ Phase Two of new ship models, the Sabre was designed as a space superiority fighter for those situations where you need to leave a lighter footprint. They have raised the bar yet again with their Raven variant, maintaining all the speed and maneuverability of its Sabre forebear, but with a lower ship signature, making it a fast, stealthy infiltrator.",
          url: "/pledge/ships/sabre/Sabre-Raven"
        },
        {
          id: "103",
          afterburner_speed: "0",
          beam: "50.0",
          cargocapacity: "230",
          height: "20.0",
          length: "90.0",
          manufacturer_id: "3",
          mass: "3650500",
          max_crew: "8",
          min_crew: "3",
          pitch_max: null,
          production_note: "Concept complete.",
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "large",
          time_modified: "1 year ago",
          type: "support",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A so-called “flying toolbox,” the Crucible is Anvil Aerospace’s first dedicated repair ship. Featuring a rotating control bridge and a detachable pressurized workspace,  the Crucible is a versatile mobile garage equipped with repair arms, a drone operation center and all the equipment needed to overhaul a damaged craft back into fighting shape.",
          url: "/pledge/ships/crucible/Crucible"
        },
        {
          id: "104",
          afterburner_speed: "0",
          beam: "7.7",
          cargocapacity: "0",
          height: "2.2",
          length: "12.0",
          manufacturer_id: "19",
          mass: "8290",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "snub",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "If you’re looking for something a little more agile, blaze among the stars with Kruger Intergalactic’s P-72 Archimedes. Whether for added security, exploring a system or simply the joy of flying, the Archimedes is the perfect companion snub craft. Featuring an extra intake and a lighter hull than its sister ship, the Archimedes delivers exceptional handling and boost capabilities in a sleek package you’ll want along for the ride.",
          url: "/pledge/ships/p72-archimedes/P72-Archimedes"
        },
        {
          id: "207",
          afterburner_speed: null,
          beam: "7.7",
          cargocapacity: "0",
          height: "2.2",
          length: "12.0",
          manufacturer_id: "19",
          mass: "8979",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "250",
          size: "snub",
          time_modified: "3 months ago",
          type: "competition",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Built with exacting precision and styled with urban sophistication in mind, this compact snub isn’t just for show. Fast and responsive, it’s the ideal chaperone for larger ship or the perfect partner for a solo sprint in-atmosphere. The Archimedes Emerald features an exclusive Stellar Fortuna skin, available for a limited time only. ",
          url: "/pledge/ships/p72-archimedes/P72-Archimedes-Emerald"
        },
        {
          id: "108",
          afterburner_speed: "1240",
          beam: "20.0",
          cargocapacity: "0",
          height: "5.5",
          length: "16.5",
          manufacturer_id: "69",
          mass: "26056",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "115.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "140.0",
          scm_speed: "290",
          size: "small",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: "86.3",
          yaw_max: "115.0",
          yaxis_acceleration: "116.2",
          zaxis_acceleration: "89.5",
          description: "Vanduul light fighters, designated 'Blade', are often used as scouts and first wave assault crafts. Over the decades of conflict, they have been increasingly used to take out comm arrays and early warning systems. They have also served well as skirmisher units as their speed allows them to chase down ships attempting to flee. If engaged, expect the Blade to utilize its speed and agility to wear down your defenses.",
          url: "/pledge/ships/vanduul-blade/Blade"
        },
        {
          id: "109",
          afterburner_speed: "1210",
          beam: "15.0",
          cargocapacity: "0",
          height: "7.0",
          length: "24.0",
          manufacturer_id: "4",
          mass: "116477",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "70.0",
          production_note: "Available in Alpha 3.0.",
          production_status: "flight-ready",
          roll_max: "95.0",
          scm_speed: "200",
          size: "small",
          time_modified: "2 months ago",
          type: "industrial",
          xaxis_acceleration: "40.6",
          yaw_max: "70.0",
          yaxis_acceleration: "44.4",
          zaxis_acceleration: "42.3",
          description: "For years, the Prospector has been the universe’s preferred mining vessel for solo operators. Featuring MISC’s sleek design sensibility and a bevy of upgraded high-tech mining tools, the 2947 Prospector perfectly balances form and functionality.",
          url: "/pledge/ships/misc-prospector/Prospector"
        },
        {
          id: "110",
          afterburner_speed: "1315",
          beam: "16.0",
          cargocapacity: "0",
          height: "4.5",
          length: "15.0",
          manufacturer_id: "5",
          mass: "40821",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "110.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "150.0",
          scm_speed: "280",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "92.8",
          yaw_max: "110.0",
          yaxis_acceleration: "108.7",
          zaxis_acceleration: "92.8",
          description: "The Buccaneer has been designed from the ground up to fly and fight the way you live. No leather interiors or hyperpillows here: the ‘Bucc is a scrapper designed to maneuver and fight above its weight class. This rough-and-tumble frontier fighter can be maintained in the worst of conditions in order to keep real, working space crews alive.",
          url: "/pledge/ships/drake-buccaneer/Buccaneer"
        },
        {
          id: "111",
          afterburner_speed: "1100",
          beam: "2.5",
          cargocapacity: "0",
          height: "1.5",
          length: "6.0",
          manufacturer_id: "5",
          mass: "2169",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "90.0",
          production_note: "Available in Alpha 3.0.",
          production_status: "flight-ready",
          roll_max: "110.0",
          scm_speed: "155",
          size: "snub",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "50.6",
          yaw_max: "80.0",
          yaxis_acceleration: "67.4",
          zaxis_acceleration: "60.8",
          description: "The Drake Dragonfly is the perfect snub ship for anyone looking to live on the edge. With nothing separating the pilot from the dangers of space, the Dragonfly is as much an adventure as a ship! Dual-mode conversion allows the Dragonfly to operate on the ground or in space, and a rear-facing second seat means you can even take a passenger! This exclusive Yellowjacket version is available only for the concept sale.\n",
          url: "/pledge/ships/drake-dragonfly/Dragonfly-Yellowjacket"
        },
        {
          id: "112",
          afterburner_speed: "1100",
          beam: "2.5",
          cargocapacity: "0",
          height: "1.5",
          length: "6.0",
          manufacturer_id: "5",
          mass: "2169",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "115.0",
          production_note: "Available in Alpha 3.0.",
          production_status: "flight-ready",
          roll_max: "175.0",
          scm_speed: "255",
          size: "snub",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "50.6",
          yaw_max: "105.0",
          yaxis_acceleration: "67.4",
          zaxis_acceleration: "60.8",
          description: "The Drake Dragonfly is the perfect snub ship for anyone looking to live on the edge. With nothing separating the pilot from the dangers of space, the Dragonfly is as much an adventure as a ship! Dual-mode conversion allows the Dragonfly to operate on the ground or in space, and a rear-facing second seat means you can even take a passenger! This black model is Drake's standard production version.\n",
          url: "/pledge/ships/drake-dragonfly/Dragonfly-Black"
        },
        {
          id: "113",
          afterburner_speed: "920",
          beam: "8.5",
          cargocapacity: "0",
          height: "4.3",
          length: "9.3",
          manufacturer_id: "73",
          mass: "12307",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "50.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "80.0",
          scm_speed: "150",
          size: "snub",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: "25.8",
          yaw_max: "50.0",
          yaxis_acceleration: "29.3",
          zaxis_acceleration: "27.2",
          description: "The ARGO Astronautics MPUV-1P (commonly ‘Argo Personnel.’) is geared towards a simple but incredibly important responsibility: moving groups of people from place to place. The UEE Navy uses MPUV-1Ps extensively, and any new recruit can likely recall those terrifying moments in which such a ship carried them to their first space assignment. In civilian hands, Argo Personnel ships are adapted for everything from standard taxi services to use as makeshift combat dropships. The ARGO is capable of carrying up to eight Humans and their equipment.",
          url: "/pledge/ships/argo/MPUV-Personnel"
        },
        {
          id: "114",
          afterburner_speed: "900",
          beam: "8.5",
          cargocapacity: "2",
          height: "4.3",
          length: "9.5",
          manufacturer_id: "73",
          mass: "12187",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "50.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "80.0",
          scm_speed: "150",
          size: "snub",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: "25.8",
          yaw_max: "50.0",
          yaxis_acceleration: "29.3",
          zaxis_acceleration: "27.2",
          description: "The ARGO Astronautics MPUV-1C (commonly ‘Argo Cargo’) is a dedicated merchant transfer ship, a ubiquitous intergalactic stevedore. Vast numbers of Argo Cargos are responsible for loading and unloading goods onto massive long-haul transports and miners that cannot otherwise land on planets or drydocks, such as the Hull D and the Orion. Some captains choose to own and operate their own Argo, while others pay privately owned ships operating as port services a rental fee for performing the unloading process.",
          url: "/pledge/ships/argo/MPUV-Cargo"
        },
        {
          id: "115",
          afterburner_speed: "1205",
          beam: "14.5",
          cargocapacity: "0",
          height: "6.0",
          length: "19.5",
          manufacturer_id: "3",
          mass: "86454",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "75.0",
          production_note: "Currently being built and tested for implementation in-game.",
          production_status: "flight-ready",
          roll_max: "100.0",
          scm_speed: "210",
          size: "small",
          time_modified: "1 year ago",
          type: "exploration",
          xaxis_acceleration: "51.9",
          yaw_max: "75.0",
          yaxis_acceleration: "65.7",
          zaxis_acceleration: "58.1",
          description: "Presenting the Anvil Aerospace U4A-3 Terrapin-class Scanning/Exploration Ship. The Terrapin was developed near the end of the 28th century to serve as the first ship in the Empire’s defensive restructuring of the Navy. The Terrapin’s watchword is protection, with extensive shield systems and armor layers designed to provide the maximum possible defense for pilot and crew. While it lacks the maneuverability of a dedicated fighter, it does maintain an advanced, hard-hitting array of weapons intended to keep the most fearsome Vanduul raider at bay.",
          url: "/pledge/ships/terrapin/Terrapin"
        },
        {
          id: "116",
          afterburner_speed: "0",
          beam: "82.0",
          cargocapacity: "216",
          height: "35.0",
          length: "155.0",
          manufacturer_id: "1",
          mass: "17155000",
          max_crew: "14",
          min_crew: "6",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "capital",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Polaris is a nimble corvette-class capital ship that packs a powerful punch with a full armament of turrets and torpedoes. Intended for use as both a naval patrol ship and to serve as the flagship of militia operations, Polaris has the capacity to perform search and rescue operations, light strike missions and general security patrols. The Polaris includes the facilities to repair, rearm and refuel a single fighter, light bomber or support ship.",
          url: "/pledge/ships/polaris/Polaris"
        },
        {
          id: "117",
          afterburner_speed: "1116",
          beam: "32.0",
          cargocapacity: "0",
          height: "15.0",
          length: "34.0",
          manufacturer_id: "69",
          mass: "171700",
          max_crew: "2",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "178",
          size: "medium",
          time_modified: "3 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Named after the UPE military designation, the Prowler is a modernized version of the infamous Tevarin armored personnel carrier. Esperia’s astroengineers were given unmitigated access to study original versions of the ship recently discovered in the Kabal system to help meticulously reconstruct the vehicle. Now, the Prowler is the perfect fusion of two cultures: the elegance and effectiveness of the Tevarin war machine combined with the reliability of modern Human technology.   \n",
          url: "/pledge/ships/prowler/Prowler"
        },
        {
          id: "123",
          afterburner_speed: "1185",
          beam: "10.0",
          cargocapacity: "0",
          height: "2.0",
          length: "13.0",
          manufacturer_id: "6",
          mass: "19097",
          max_crew: "2",
          min_crew: "1",
          pitch_max: "100.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "135.0",
          scm_speed: "255",
          size: "snub",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: "59.0",
          yaw_max: "100.0",
          yaxis_acceleration: "68.2",
          zaxis_acceleration: "61.3",
          description: "Elegantly styled and meticulously constructed, the 85X is a versatile and comprehensive away-vessel that features precision control in and out of atmosphere. Utilizing much of the same thruster technology as the 300 series, it has the power of a racer with the reliability of a touring ship. Whether descending down to the planet surface or taking in the sights of your system, this runabout continues Origin’s proud tradition of turning heads.\n",
          url: "/pledge/ships/85x/85X"
        },
        {
          id: "126",
          afterburner_speed: "1345",
          beam: "8.2",
          cargocapacity: "0",
          height: "2.7",
          length: "11.5",
          manufacturer_id: "4",
          mass: "10925",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "127.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "172.0",
          scm_speed: "335",
          size: "small",
          time_modified: "2 months ago",
          type: "competition",
          xaxis_acceleration: "89.7",
          yaw_max: "127.0",
          yaxis_acceleration: "120.0",
          zaxis_acceleration: "98.6",
          description: "MISC makes a bid for the next Murray Cup with the all-new Razor. This advanced racer features an advanced composite spaceframe that puts pure speed ahead of everything else... it's the ship for pilots who want to leave the competition in the dust.",
          url: "/pledge/ships/razor/Razor"
        },
        {
          id: "157",
          afterburner_speed: "1340",
          beam: "8.2",
          cargocapacity: "0",
          height: "2.7",
          length: "11.5",
          manufacturer_id: "4",
          mass: "10925",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "127.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "172.0",
          scm_speed: "325",
          size: "small",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "89.3",
          yaw_max: "127.0",
          yaxis_acceleration: "119.0",
          zaxis_acceleration: "98.1",
          description: "Outfitted with signature-reducing materials, the RAZOR-EX was a specialty build for the UEE Advocacy for use in surveillance and extraction operations. Although the EX was ultimately rejected for widespread use, MISC released a variation of the model for the public who were looking to keep a lower profile.",
          url: "/pledge/ships/razor/Razor-EX"
        },
        {
          id: "158",
          afterburner_speed: "1345",
          beam: "8.2",
          cargocapacity: "0",
          height: "2.7",
          length: "11.5",
          manufacturer_id: "4",
          mass: "10925",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "127.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "172.0",
          scm_speed: "340",
          size: "small",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: "89.4",
          yaw_max: "127.0",
          yaxis_acceleration: "119.1",
          zaxis_acceleration: "98.2",
          description: "The Razor gets supercharged. The LX features an overclocked engine to unleash blazing top speeds perfect. This power comes at a cost with reduced maneuverability and armaments making it ideal for straight-shot racing. But who needs weapons when you’re leaving your competition in the dust.",
          url: "/pledge/ships/razor/Razor-LX"
        },
        {
          id: "128",
          afterburner_speed: "1125",
          beam: "14.5",
          cargocapacity: "0",
          height: "6.0",
          length: "22.0",
          manufacturer_id: "3",
          mass: "86454",
          max_crew: "2",
          min_crew: "2",
          pitch_max: "100.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "140.0",
          scm_speed: "265",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: "67.6",
          yaw_max: "100.0",
          yaxis_acceleration: "84.5",
          zaxis_acceleration: "69.6",
          description: "Big things do come in small packages: the Hurricane is a fighting spacecraft that packs a deadly punch into a slight fuselage. The spacecraft compensates for its lack of creature comforts with its powerful armament - six guns capable of blasting their way through nearly anything. Hurricane pilots have yet to find an enemy shield they can't knock down.",
          url: "/pledge/ships/hurricane/Hurricane"
        },
        {
          id: "129",
          afterburner_speed: "0",
          beam: "20.0",
          cargocapacity: "0",
          height: "8.0",
          length: "25.5",
          manufacturer_id: "21",
          mass: "78406",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "small",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Meet the Banu Defender, a multi-crew fighter whose patchwork design highlights technology from a variety of species. Though cargo space is limited, the Defender features modest accommodations for its crew and provides easy access to components. The Defender gets its name from the role it serves: the first line of defense against enemy attacks. That’s why the Defender makes the ideal companion to the Merchantman: one to do the heavy hauling and the other to perform the deadly dogfighting. Every Banu merchant knows an investment in defense is an investment in their livelihood.",
          url: "/pledge/ships/defender/Banu-Defender"
        },
        {
          id: "130",
          afterburner_speed: "980",
          beam: "36.6",
          cargocapacity: "0",
          height: "4.4",
          length: "20.5",
          manufacturer_id: "12",
          mass: "54216",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "75.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "120.0",
          scm_speed: "195",
          size: "medium",
          time_modified: "4 months ago",
          type: "combat",
          xaxis_acceleration: "47.9",
          yaw_max: "75.0",
          yaxis_acceleration: "61.1",
          zaxis_acceleration: "51.2",
          description: "The Aegis Eclipse is a bomber designed to get in and strike before it's even spotted. After extensive service with the UEE, this high-tech military stalwart is making its debut on the civilian market for 2947.",
          url: "/pledge/ships/eclipse/Eclipse"
        },
        {
          id: "131",
          afterburner_speed: "1105",
          beam: "1.5",
          cargocapacity: "0",
          height: "1.5",
          length: "5.5",
          manufacturer_id: "81",
          mass: "1394",
          max_crew: "1",
          min_crew: "1",
          pitch_max: "125.0",
          production_note: "Available in Alpha 3.0.",
          production_status: "flight-ready",
          roll_max: "175.0",
          scm_speed: "275",
          size: "snub",
          time_modified: "3 months ago",
          type: "competition",
          xaxis_acceleration: "56.0",
          yaw_max: "110.0",
          yaxis_acceleration: "70.7",
          zaxis_acceleration: "60.6",
          description: "Hit the skids with the 2947 Nox. This speedy and maneuverable open-canopy racer from Aopoa is capable of zipping along planet surfaces or deep space. Available for the first time in Human space, the Nox has been specifically redesigned for Human pilots, so grab your ship and head to the racetrack today.\n",
          url: "/pledge/ships/nox/Nox"
        },
        {
          id: "132",
          afterburner_speed: "1103",
          beam: "1.5",
          cargocapacity: "0",
          height: "1.5",
          length: "5.5",
          manufacturer_id: "81",
          mass: "1394",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "220",
          size: "snub",
          time_modified: "3 months ago",
          type: "competition",
          xaxis_acceleration: "56.0",
          yaw_max: null,
          yaxis_acceleration: "70.7",
          zaxis_acceleration: "60.6",
          description: "Deriving its name from the Xi’an word for ‘thrust,’ the Nox Kue delivers that and more. This limited version of the open-canopy racer features a stunning brushed-silver finish and was specifically created to celebrate the inaugural sale of the first Nox for Human riders.\n",
          url: "/pledge/ships/nox/Nox-Kue"
        },
        {
          id: "134",
          afterburner_speed: "0",
          beam: "4.0",
          cargocapacity: "1",
          height: "2.5",
          length: "6.0",
          manufacturer_id: "83",
          mass: "3022",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With a potent combination of speed, maneuverability, and rugged durability, the Cyclone is a perfect choice for local deliveries and transport between planetside homesteads and outposts.",
          url: "/pledge/ships/cyclone/Cyclone"
        },
       
      ]);
    });
};
