
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('ship_specs4')
  .truncate()
    .then(function () {
      // Inserts seed entries
      return knex('ship_specs4').insert([
        {
          id: "135",
          afterburner_speed: "0",
          beam: "4.0",
          cargocapacity: "0",
          height: "2.5",
          length: "6.0",
          manufacturer_id: "83",
          mass: "3022",
          max_crew: "3",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Designed for militia and security use, the Cyclone TR module features upgraded armor and a single Human-operated turret capable of mounting a Size 1 weapon and a responsive 360° field of fire.",
          url: "/pledge/ships/cyclone/Cyclone-TR"
        },
        {
          id: "136",
          afterburner_speed: "0",
          beam: "4.0",
          cargocapacity: "0",
          height: "2.5",
          length: "6.0",
          manufacturer_id: "83",
          mass: "3022",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "For those who like to push the limits of speed, the Cyclone RC features a modified intake system to allow for controlled bursts of speed as well as tools to customize handling.",
          url: "/pledge/ships/cyclone/Cyclone-RC"
        },
        {
          id: "137",
          afterburner_speed: "0",
          beam: "4.0",
          cargocapacity: "0",
          height: "3.0",
          length: "6.0",
          manufacturer_id: "83",
          mass: "3022",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Stay mobile and aware with the Cyclone RN. This light reconnaissance vehicle is the perfect solution for scouting runs, providing fast and detailed scans of terrain as well as beacon placement.",
          url: "/pledge/ships/cyclone/Cyclone-RN"
        },
        {
          id: "138",
          afterburner_speed: "0",
          beam: "4.0",
          cargocapacity: "0",
          height: "2.5",
          length: "6.0",
          manufacturer_id: "83",
          mass: "3300",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "0",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A battlefield equalizer, the Cyclone AA comes equipped with a surface-to-air missile and countermeasure package to provide cover for ground troops against airborne targets.",
          url: "/pledge/ships/cyclone/Cyclone-AA"
        },
        {
          id: "139",
          afterburner_speed: "0",
          beam: "5.5",
          cargocapacity: "4",
          height: "2.2",
          length: "7.6",
          manufacturer_id: "1",
          mass: "11732",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: "Available in Alpha 3.0.",
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "40",
          size: "vehicle",
          time_modified: "2 months ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Built by RSI specifically for the planetside explorer, the Ursa Rover offers civilians military-grade all-terrain capabilities and stands as the rugged standard in ground-based scouting, mapping and discovery applications.",
          url: "/pledge/ships/ursa/Ursa-Rover"
        },
        {
          id: "179",
          afterburner_speed: "0",
          beam: "5.5",
          cargocapacity: "4",
          height: "2.2",
          length: "7.6",
          manufacturer_id: "1",
          mass: "11732",
          max_crew: "2",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "40",
          size: "vehicle",
          time_modified: "2 months ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Fortune favors the bold. The most trusted name in all-terrain exploration embodies the essence of good fortune and success with this commemorative limited-edition Ursa Rover.",
          url: "/pledge/ships/ursa/Ursa-Rover-Fortuna"
        },
        {
          id: "140",
          afterburner_speed: "950",
          beam: "52.0",
          cargocapacity: "16",
          height: "17.0",
          length: "91.5",
          manufacturer_id: "6",
          mass: "1576792",
          max_crew: "5",
          min_crew: "3",
          pitch_max: "30.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "50.0",
          scm_speed: "135",
          size: "large",
          time_modified: "1 year ago",
          type: "exploration",
          xaxis_acceleration: "13.1",
          yaw_max: "30.0",
          yaxis_acceleration: "14.6",
          zaxis_acceleration: "14.2",
          description: "Let the voyage begin with the 2947 600i from Origin Jumpworks. This multi-role luxury vessel from Origin Jumpworks features an exquisitely detailed hull design that balances performance and versatility in a sleek and timeless form. The 600i is designed with a cutting-edge modular technology, allowing you to customize your ship for your needs. Taking the family on a long-distance trip across the stars? The Touring module lets your guests relax in ease with stunning furniture from some of the Empire's top designers.",
          url: "/pledge/ships/600i/600i-Touring"
        },
        {
          id: "141",
          afterburner_speed: "975",
          beam: "52.0",
          cargocapacity: "40",
          height: "17.0",
          length: "91.5",
          manufacturer_id: "6",
          mass: "1576792",
          max_crew: "5",
          min_crew: "2",
          pitch_max: "30.0",
          production_note: null,
          production_status: "flight-ready",
          roll_max: "50.0",
          scm_speed: "145",
          size: "large",
          time_modified: "4 months ago",
          type: "exploration",
          xaxis_acceleration: "15.6",
          yaw_max: "30.0",
          yaxis_acceleration: "21.6",
          zaxis_acceleration: "18.1",
          description: "Let the voyage begin with the 2947 600i from Origin Jumpworks. This multi-role luxury vessel from Origin Jumpworks features an exquisitely detailed hull design that balances performance and versatility in a sleek and timeless form. The 600i is designed with a cutting-edge modular technology, allowing you to customize your ship for your needs. Looking to stamp your name in history with the discovery of a new star system? The 600i's Explorer module swaps the lounge for a robust scanning station as well as additional utility hardpoints to increase the ship's effectiveness even more.",
          url: "/pledge/ships/600i/600i-Explorer"
        },
        {
          id: "143",
          afterburner_speed: "0",
          beam: "1.3",
          cargocapacity: "0",
          height: "1.5",
          length: "5.5",
          manufacturer_id: "6",
          mass: "1610",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "snub",
          time_modified: "1 year ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Welcome to the next level with the X1, Origin Jumpwork's new high performance open-canopy vehicle. Built from lightweight polymers, the X1 takes speed and agility to the next level thanks to seamlessly integrated engine technology and joint vector thruster placement. Innovative design and high quality engineering weave together to create a flight experience like no other.",
          url: "/pledge/ships/x1/X1-Base"
        },
        {
          id: "145",
          afterburner_speed: "0",
          beam: "1.3",
          cargocapacity: "0",
          height: "1.5",
          length: "5.5",
          manufacturer_id: "6",
          mass: "1528",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "snub",
          time_modified: "1 year ago",
          type: "competition",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "How do you make fast go faster? Origin Jumpworks X1 Velocity dares to push the boundaries of speed by stripping down the base X1 to its core elements; eliminating the weapon mount and incorporating new Syntek composites to create a lighter chassis for overall weight loss.",
          url: "/pledge/ships/x1/X1-Velocity"
        },
        {
          id: "147",
          afterburner_speed: "0",
          beam: "1.3",
          cargocapacity: "0",
          height: "1.5",
          length: "5.5",
          manufacturer_id: "6",
          mass: "1682",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "0",
          size: "snub",
          time_modified: "1 year ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Built to endure tougher environments and look good doing it, the X1 Force is a modified version of the base X1 model, featuring additional defensive elements to toughen up this speedy and agile open canopy bike, allowing it to serve in a variety of roles, from exploring worlds to potential security infiltration ops.",
          url: "/pledge/ships/x1/X1-Force"
        },
        {
          id: "149",
          afterburner_speed: null,
          beam: "125.0",
          cargocapacity: "600",
          height: "30.0",
          length: "200.0",
          manufacturer_id: "22",
          mass: "35600000",
          max_crew: "8",
          min_crew: "4",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "85",
          size: "capital",
          time_modified: "1 year ago",
          type: "multi",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "After their auspicious debut with the Mustang, Consolidated Outland has gone and changed the game again with the reveal of the Pioneer. This self-contained mobile construction yard is capable of creating planetary modular structures, ushering a new wave of aspiring colonists to customize their new homes on the frontier.",
          url: "/pledge/ships/pioneer/Pioneer"
        },
        {
          id: "150",
          afterburner_speed: "500",
          beam: "22.0",
          cargocapacity: "0",
          height: "6.5",
          length: "17.0",
          manufacturer_id: "3",
          mass: "40000",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "200",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A small, light fighter with an emphasis on weaponry, the Hawk boasts an impressive arsenal of lethal and non-lethal weapons, making it a perfect ship for independent bounty hunters or local security looking for a little more punch.",
          url: "/pledge/ships/hawk/Hawk"
        },
        {
          id: "151",
          afterburner_speed: null,
          beam: "75.0",
          cargocapacity: "40",
          height: "16.0",
          length: "115.0",
          manufacturer_id: "12",
          mass: "4260000",
          max_crew: "9",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: null,
          size: "large",
          time_modified: "2 months ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A fast patrol ship with multiple turrets designed to combat fighters, the Hammerhead is equally suited to support larger capital ships in a fleet or act as a flagship for fighter groups.",
          url: "/pledge/ships/hammerhead/Hammerhead"
        },
        {
          id: "195",
          afterburner_speed: null,
          beam: "75.0",
          cargocapacity: "40",
          height: "16.0",
          length: "115.0",
          manufacturer_id: "12",
          mass: "4260000",
          max_crew: "9",
          min_crew: "3",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: null,
          size: "large",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "A fast patrol ship with multiple turrets designed to combat fighters, the Hammerhead is equally suited to support larger capital ships in a fleet or act as a flagship for fighter groups.",
          url: "/pledge/ships/hammerhead/Hammerhead-Best-In-Show-Edition"
        },
        {
          id: "154",
          afterburner_speed: null,
          beam: "7.0",
          cargocapacity: "0",
          height: "5.0",
          length: "16.0",
          manufacturer_id: "83",
          mass: null,
          max_crew: "3",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "20",
          size: "vehicle",
          time_modified: "1 year ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Tumbril's new Nova is a classic battlefield warrior, reimagined for the modern age. This heavy tank offers a devastating combination of weaponry to eliminate threats on the ground and in the air.",
          url: "/pledge/ships/nova-tank/Nova"
        },
        {
          id: "155",
          afterburner_speed: null,
          beam: "16.5",
          cargocapacity: "12",
          height: "10.0",
          length: "38.5",
          manufacturer_id: "12",
          mass: "625330",
          max_crew: "3",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "210",
          size: "medium",
          time_modified: "1 year ago",
          type: "multi",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Refuel. Repair. Rearm. Become a one-person support crew with Aegis Dynamics’ versatile Vulcan, supplying aid to pilots on the fly. Whether pinned down under heavy fire and in need of ammunition, low on quantum fuel after an ill-planned jump, or stranded in unknown space with a busted thruster, a pilot in distress can always count on a Vulcan and its cadre of drones to lend speedy, efficient assistance. \n\nOutfit your Vulcan with eye-catching livery and become a beacon of hope, even in the darkest, most treacherous corners of the ‘verse.",
          url: "/pledge/ships/vulcan/Vulcan"
        },
        {
          id: "159",
          afterburner_speed: null,
          beam: "11.0",
          cargocapacity: "2",
          height: "4.0",
          length: "19.3",
          manufacturer_id: "6",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "210",
          size: "small",
          time_modified: "2 weeks ago",
          type: "multi",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Tour the universe with the perfect coupling of luxury and performance. The 100i features Origin Jumpworks' patented AIR fuel system, making it the most efficient and eco-friendly ship on the market. Capable of long distance flights that most ships of its size aren't equipped for, the 100i is perfect for solo pilots looking to turn heads without sacrificing functionality or reliability.",
          url: "/pledge/ships/origin-100/100i"
        },
        {
          id: "160",
          afterburner_speed: null,
          beam: "11.0",
          cargocapacity: "2",
          height: "4.0",
          length: "19.3",
          manufacturer_id: "6",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "230",
          size: "small",
          time_modified: "2 weeks ago",
          type: "multi",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Risks were meant to be taken, but why risk running out of fuel in the heat of battle? With the AIR fuel system, a souped-up weapons package, and all the luxury and refinement you've come to expect from Origin Jumpworks, the 125a has been designed for the discerning maverick.",
          url: "/pledge/ships/origin-100/125a"
        },
        {
          id: "161",
          afterburner_speed: null,
          beam: "11.0",
          cargocapacity: "6",
          height: "4.0",
          length: "19.3",
          manufacturer_id: "6",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "190",
          size: "small",
          time_modified: "2 weeks ago",
          type: "multi",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With a deceptive amount of storage space in its sleek, stylish frame, and Origin's patented AIR fuel system, the 135c model is the obvious choice for musicians, couriers, and anyone trying to get the party started. Get it there fast, and look good while you're doing it.",
          url: "/pledge/ships/origin-100/135c"
        },
        {
          id: "162",
          afterburner_speed: null,
          beam: "70.0",
          cargocapacity: "624",
          height: "23.0",
          length: "94.0",
          manufacturer_id: "68",
          mass: null,
          max_crew: "2",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "135",
          size: "large",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Utilizing the patented Hercules military-grade spaceframe and expanding cargo capacity, while sacrificing barely any firepower, the C2 has taken the private sector by storm. It has become the industry standard for racing teams, ship dealers and manufacturers, construction orgs, mining corporations, and even large-scale touring entertainment outfits. ",
          url: "/pledge/ships/crusader-starlifter/C2-Hercules"
        },
        {
          id: "163",
          afterburner_speed: null,
          beam: "70.0",
          cargocapacity: "468",
          height: "23.0",
          length: "94.0",
          manufacturer_id: "68",
          mass: null,
          max_crew: "3",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "130",
          size: "large",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The M2 Hercules is the UEE's premier tactical starlifter. The ship's potent combination of capacity, maneuverability, and durability make it the obvious choice in large-scale transport, and a robust weapons package assures your cargo, and crew, gets to where they’re going in one piece.",
          url: "/pledge/ships/crusader-starlifter/M2-Hercules"
        },
        {
          id: "164",
          afterburner_speed: null,
          beam: "70.0",
          cargocapacity: "234",
          height: "23.0",
          length: "94.0",
          manufacturer_id: "68",
          mass: null,
          max_crew: "8",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "130",
          size: "large",
          time_modified: "1 year ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The A2 gunship has been used to devastating effect in airborne assaults, search and rescue operations, and landing initiatives. With more than double the firepower of the M2, and a custom bomb bay capable of delivering a staggering payload, the A2 caters to anyone hauling massive amounts of cargo through potentially unfriendly skies.",
          url: "/pledge/ships/crusader-starlifter/A2-Hercules"
        },
        {
          id: "165",
          afterburner_speed: null,
          beam: "16.0",
          cargocapacity: "12",
          height: "9.0",
          length: "33.0",
          manufacturer_id: "5",
          mass: "114591",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "165",
          size: "small",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Answer to no one, cut out the middle man, and throw caution to the wind. Rip wrecks like a pro and carve out your own place in the great big empty behind the stick of this rough, rugged salvage machine from Drake Interplanetary. ",
          url: "/pledge/ships/drake-vulture/Vulture"
        },
        {
          id: "166",
          afterburner_speed: null,
          beam: "30.0",
          cargocapacity: "28",
          height: "10.0",
          length: "43.0",
          manufacturer_id: "1",
          mass: "376500",
          max_crew: "2",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "205",
          size: "large",
          time_modified: "10 months ago",
          type: "support",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The legendary Apollo chassis from Roberts Space Industries is the gold standard in medevac and rapid emergency response, having provided critical aid to the known universe for well over two centuries.",
          url: "/pledge/ships/rsi-apollo/Apollo-Triage"
        },
        {
          id: "167",
          afterburner_speed: null,
          beam: "30.0",
          cargocapacity: "28",
          height: "10.0",
          length: "43.0",
          manufacturer_id: "1",
          mass: "376500",
          max_crew: "2",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "195",
          size: "large",
          time_modified: "10 months ago",
          type: "support",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Along with superior armor and dual missile racks, the 2948 Apollo Medivac model pays homage to the classic 2910 film, Astromedics: Back from the Brink, with livery that accurately recreates the headlining Kithara. ",
          url: "/pledge/ships/rsi-apollo/Apollo-Medivac"
        },
        {
          id: "168",
          afterburner_speed: "1050",
          beam: "38.0",
          cargocapacity: "96",
          height: "11.6",
          length: "40.0",
          manufacturer_id: "68",
          mass: null,
          max_crew: "3",
          min_crew: "2",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "215",
          size: "medium",
          time_modified: "10 months ago",
          type: "transport",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Mercury checks all the boxes expected of a dependable courier vessel, and then some. If you need it there fast and unscathed, you can’t do better than the Mercury. Built with the same engineering and design principals that has made Crusader the go-to manufacturer for galactic transport on any scale, the star runner chassis sets new standards for data and cargo conveyance.",
          url: "/pledge/ships/crusader-mercury-star-runner/Mercury-Star-Runner"
        },
        {
          id: "169",
          afterburner_speed: null,
          beam: "28.0",
          cargocapacity: null,
          height: "9.5",
          length: "38.0",
          manufacturer_id: "3",
          mass: null,
          max_crew: "5",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: null,
          size: "small",
          time_modified: "2 months ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "In the days of antiquity, the Valkyrie were believed to choose who would live and who would die on the field of war. Now, Anvil is putting that choice in your hands. Seize fate and turn the tide of battle.\n\nRugged, high-performance jump seats safely transport up to twenty personnel into and out of the fray. A vehicle bay and speed ramp efficiently launch ground-based transport or reconnaissance vehicles for unmatched support. Four powerful VTOL thrusters facilitate surgically precise take-offs and landings, while a devastating array of weaponry blurs the line between dropship and gunship.",
          url: "/pledge/ships/anvil-valkyrie/Valkyrie"
        },
        {
          id: "171",
          afterburner_speed: null,
          beam: "28.0",
          cargocapacity: null,
          height: "9.5",
          length: "38.0",
          manufacturer_id: "3",
          mass: "75000",
          max_crew: "5",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: null,
          size: "small",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "For over a century, Anvil ships have distinguished themselves in countless civilian and military combat operations. Honor that proud tradition with the limited Liberator Edition Valkyrie, featuring an exclusive trim package commemorating the dropship's debut at CitizenCon 2948.",
          url: "/pledge/ships/anvil-valkyrie/Valkyrie-Liberator-Edition"
        },
        {
          id: "170",
          afterburner_speed: null,
          beam: "104.0",
          cargocapacity: "3792",
          height: "64.0",
          length: "270.0",
          manufacturer_id: "5",
          mass: null,
          max_crew: "10",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "capital",
          time_modified: "2 years ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Kraken is a protector and a beacon of freedom in a too-often cruel universe. For those tasked with safekeeping Citizens unable to protect themselves, the Kraken is both a sanctuary and a self-contained war machine ready to take on the most daunting adversaries. Drake has thrown out the rule book to redefine private-use capital-class ships, attack carriers, and the very nature of personal freedom. It's nothing if not a testament to the empowerment of the people.",
          url: "/pledge/ships/drake-kraken/Kraken"
        },
        {
          id: "175",
          afterburner_speed: null,
          beam: "104.0",
          cargocapacity: "768",
          height: "64.0",
          length: "270.0",
          manufacturer_id: "5",
          mass: null,
          max_crew: "10",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "capital",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "The Kraken is a protector and a beacon of freedom in a too-often cruel universe. For those tasked with safekeeping Citizens unable to protect themselves, the Kraken is both a sanctuary and a self-contained war machine ready to take on the most daunting adversaries. Drake has thrown out the rule book to redefine private-use capital-class ships, attack carriers, and the very nature of personal freedom. It's nothing if not a testament to the empowerment of the people.",
          url: "/pledge/ships/drake-kraken/Kraken-Privateer"
        },
        {
          id: "173",
          afterburner_speed: null,
          beam: "12.0",
          cargocapacity: "0",
          height: "4.0",
          length: "16.0",
          manufacturer_id: "3",
          mass: "30752",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "flight-ready",
          roll_max: null,
          scm_speed: "270",
          size: "small",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Meet Anvil's ‘light fighter of the future’. Featuring an ultra-aerodynamic frame, slight profile, and the most advanced manoeuvring thruster tech available, it’s the most agile ship in its class. It can also hold its own in a knock-down-drag-out thanks to a generous standard weapons package that includes quad missile racks and a full complement of countermeasures. The Arrow is designed specifically to leave would-be interlopers thoroughly bewildered. After all, how can they kill what they can't catch?",
          url: "/pledge/ships/anvil-arrow/Arrow"
        },
        {
          id: "174",
          afterburner_speed: null,
          beam: "23.0",
          cargocapacity: "0",
          height: "10.0",
          length: "24.0",
          manufacturer_id: "81",
          mass: "106566",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "265",
          size: "medium",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Harnessing the power of next-generation Xi'an flight systems, upgraded dual-vector thrusters, and a daunting weapons package, Aopoa has crafted a fighter that retains the nimble dexterity and tight handling the brand is known for. All with the added ability to pack a serious wallop when the situation calls for it. Welcome to the future of spaceflight, courtesy of the Xi'an Empire and Aopoa.",
          url: "/pledge/ships/aopoa-santokyai/Santoky-i"
        },
        {
          id: "176",
          afterburner_speed: null,
          beam: "19.5",
          cargocapacity: "10",
          height: "8.7",
          length: "28.5",
          manufacturer_id: "73",
          mass: "231680",
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: "200",
          size: "small",
          time_modified: "1 year ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "When it comes to getting the job done, ARGO doesn’t mess around. From simple freight and cargo towing to harrowing search-and-rescue operations, the SRV handles whatever you can throw at it. The bespoke tractor system utilizes an innovative plate and arm combination, allowing for effortless solo use as well as precision team towing for bigger jobs. Your crew and passengers stay safe too thanks to durable shields and heavy-duty armor that keep the cockpit and components secure when the situation gets hairy.",
          url: "/pledge/ships/argo-srv/SRV"
        },
        {
          id: "178",
          afterburner_speed: null,
          beam: "27.0",
          cargocapacity: "72",
          height: "31.0",
          length: "55.0",
          manufacturer_id: "5",
          mass: null,
          max_crew: "4",
          min_crew: null,
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "large",
          time_modified: "10 months ago",
          type: "exploration",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "Heed the call of uncharted space and harness the spirit of exploration with the Drake Corsair, a worthy companion, supporting you in battle, discovery, and delivery, wherever the winds of adventure may steer you. ",
          url: "/pledge/ships/drake-corsair/Corsair"
        },
        {
          id: "180",
          afterburner_speed: null,
          beam: "2.0",
          cargocapacity: "0",
          height: "2.0",
          length: "3.7",
          manufacturer_id: "83",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "vehicle",
          time_modified: "4 months ago",
          type: "ground",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With a streamlined frame, proprietary X-TEC adaptive tread tires, and Reactive Response precision steering and braking, the Tumbril Ranger lets you embrace the renegade spirit of the open road while staying thoroughly grounded. Put the hammer down and pump up the adrenaline with the Ranger RC, tuned for maximum speed and response with advanced propulsion and chassis technology. ",
          url: "/pledge/ships/tumbril-ranger/Ranger-RC"
        },
        {
          id: "181",
          afterburner_speed: null,
          beam: "2.0",
          cargocapacity: "0",
          height: "2.0",
          length: "3.7",
          manufacturer_id: "83",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "vehicle",
          time_modified: "1 year ago",
          type: "combat",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With a powerful frame, proprietary X-TEC adaptive tread tires, and Reactive Response precision steering and braking, the Tumbril Ranger lets you embrace the renegade spirit of the open road while staying thoroughly grounded. But adventure doesn't always go to plan, so the Ranger TR comes equipped with dual weapon mounts to make sure you're more than covered.",
          url: "/pledge/ships/tumbril-ranger/Ranger-TR"
        },
        {
          id: "182",
          afterburner_speed: null,
          beam: "2.0",
          cargocapacity: "0",
          height: "2.0",
          length: "3.7",
          manufacturer_id: "83",
          mass: null,
          max_crew: "1",
          min_crew: "1",
          pitch_max: null,
          production_note: null,
          production_status: "in-concept",
          roll_max: null,
          scm_speed: null,
          size: "vehicle",
          time_modified: "4 months ago",
          type: "industrial",
          xaxis_acceleration: null,
          yaw_max: null,
          yaxis_acceleration: null,
          zaxis_acceleration: null,
          description: "With a powerful frame, proprietary X-TEC adaptive tread tires, and Reactive Response precision steering and braking, the Tumbril Ranger lets you embrace the renegade spirit of the open road while staying thoroughly grounded. Born to tame the wild frontier, the Ranger CV takes adventure touring to the next level and delivers the goods with an auxiliary fuel tank and custom 0.375 SCU pannier. ",
          url: "/pledge/ships/tumbril-ranger/Ranger-CV"
        },
        
      ]);
    });
};
